from playwright.sync_api import sync_playwright
R=[]
def T(n,ok,d=''): R.append(ok); print(('✅ ' if ok else '❌ ')+n+('' if ok else '  → '+str(d)))
with sync_playwright() as p:
    b=p.chromium.launch(args=["--no-sandbox"]); pg=b.new_page(viewport={'width':1440,'height':900}); errs=[]; warns=[]
    pg.on("pageerror",lambda e:errs.append(str(e)[:200])); pg.on("console",lambda m: warns.append(m.text[:200]) if '[drugbox]' in m.text else None)
    pg.goto('file://'+__import__('os').environ.get('DEMO_FILE','/tmp/drugbox_brand.html'),wait_until='networkidle',timeout=60000); pg.evaluate('endSplash()'); pg.wait_for_timeout(600)
    pg.click('.lg-demo'); pg.click('#loginPage .f-btn'); pg.wait_for_timeout(3300)
    if pg.locator('.tour-skip').count(): pg.click('.tour-skip')
    pg.evaluate("goto('market')"); pg.wait_for_timeout(900)
    T('no partner levels on sellers (removed by decision)', pg.locator('#mkx .dx-lvl').count()==0)
    T('glossary terms marked', pg.locator('#mkx abbr.dx-term').count()>=5, pg.locator('#mkx abbr.dx-term').count())
    pg.locator('#mkx abbr.dx-term[data-term=CEP]').first.hover(); pg.wait_for_timeout(250)
    T('hover a term → definition', 'Certificate of Suitability' in pg.inner_text('#dxTerm'))
    pg.mouse.move(5,5)
    card=pg.locator('#mkx .sponsored-card').first; card.hover(); pg.wait_for_timeout(200); card.locator('.dx-qv').click(); pg.wait_for_timeout(300)
    T('quick view opens full details', pg.locator('.dbk-qv .qv-title').count()==1 and 'Metformin' in pg.inner_text('.dbk-qv'))
    pg.click('.dbk-qv [data-a=ok]'); pg.wait_for_timeout(400)
    T('quick view → contact continues to the message form', pg.locator('#dbkMsg').count()==1)
    pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(500)
    T('sending adds a minimised chat in the corner', pg.locator('#dxDock .dk-win.min').count()==1 and 'Vivian' in pg.inner_text('#dxDock .dk-h'))
    pg.locator('#dxDock .dk-h').click(); pg.wait_for_timeout(200)
    pg.fill('#dxDock .dk-f input','Can you ship 1 MT by November?'); pg.keyboard.press('Enter'); pg.wait_for_timeout(2300)
    T('chat in the dock + reply', 'November' in pg.inner_text('#dxDock') and 'get back to you' in pg.inner_text('#dxDock'))
    pg.locator('#dxDock button[data-a=min]').click(); pg.wait_for_timeout(150)
    T('minimize chat', pg.locator('#dxDock .dk-win.min').count()==1)
    pg.locator('#dxDock button[data-a=full]').click(); pg.wait_for_timeout(800)
    T('open full chat → Messages with the conversation', pg.evaluate("document.body.getAttribute('data-page')")=='messages' and 'November' in pg.inner_text('#mx #messagesArea'))
    pg.evaluate("goto('market')"); pg.wait_for_timeout(800)
    pg.locator('#mkx .f-opt',has_text='USFDA').locator('input').check(); pg.wait_for_timeout(300)
    T('active filter shown as a chip', pg.locator('#mkx .dx-chip',has_text='USFDA').count()==1)
    pg.locator('#mkx .f-opt',has_text='USFDA').locator('input').uncheck(); pg.wait_for_timeout(150)
    pg.locator('#mkx .cat-item',has_text='Supply').click(); pg.wait_for_timeout(250)
    for c in ['Egypt','China']:
        box=pg.locator('#mkx .f-opt',has_text=c).locator('input')
        if box.is_checked(): box.uncheck(); pg.wait_for_timeout(120)
    pg.locator('#mkx .f-opt',has_text='India').locator('input').check(); pg.wait_for_timeout(200)
    pg.locator('#mkx .f-opt',has_text='ISO 22716').locator('input').check(); pg.wait_for_timeout(400)
    zero=pg.evaluate("[...document.querySelectorAll('#mkx #tab-browse .sponsored-card,#mkx #tab-browse .lcard,#mkx #tab-browse .scard,#mkx #tab-browse .jcard')].filter(c=>c.style.display!=='none').length")
    T('no results → suggestion to remove one filter', zero==0 and pg.locator('#mkx .dx-suggest').count()==1, (zero, pg.locator('#mkx .dx-nores').count()))
    if pg.locator('#mkx .dx-suggest').count():
        pg.click('#mkx .dx-suggest'); pg.wait_for_timeout(400)
        after=pg.evaluate("[...document.querySelectorAll('#mkx #tab-browse .sponsored-card,#mkx #tab-browse .lcard,#mkx #tab-browse .scard,#mkx #tab-browse .jcard')].filter(c=>c.style.display!=='none').length")
        T('suggestion brings results back', after>0, after)
    pg.click('#mkx .dx-chip-clear'); pg.wait_for_timeout(300)
    T('Clear all removes the chips', pg.locator('#mkx .dx-chip').count()==0)
    pg.evaluate("goto('jobs')"); pg.wait_for_timeout(600); pg.locator('#jx .mode-opt',has_text='Job Hunting').click(); pg.wait_for_timeout(300)
    T('no partner levels on employers (removed by decision)', pg.locator('#jx #huntingView .dx-lvl').count()==0)
    pg.evaluate("goto('profile')"); pg.wait_for_timeout(700)
    T('certificate wall on profile', pg.locator('.dx-certwall .cw-seal').count()==3)
    T('statuses: valid / renew / expired', pg.locator('.cw-seal.st-ok').count()==1 and pg.locator('.cw-seal.st-soon').count()==1 and pg.locator('.cw-seal.st-expired').count()==1)
    pg.locator('.ptab',has_text='Skills').click(); pg.wait_for_timeout(400)
    T('skills honeycomb', pg.locator('.dx-comb .dx-cell').count()>=6, pg.locator('.dx-comb .dx-cell').count())
    pg.locator('.dx-comb .dx-cell').first.click(); pg.wait_for_timeout(200)
    T('tap a cell to endorse', pg.locator('.dx-comb .dx-cell.done').count()==1)
    pg.evaluate("goto('feed')"); pg.wait_for_timeout(700)
    pg.locator('.post-name').first.hover(); pg.wait_for_timeout(700); pg.locator('#dxHover [data-act=msg]').click(); pg.wait_for_timeout(400)
    T('hover card → Message opens the corner chat', pg.locator('#dxDock .dk-win').count()>=1 and pg.evaluate("document.body.getAttribute('data-page')")=='feed')
    print('\nJS errors:',errs or 'none','| feature warnings:',warns or 'none'); print(sum(R),'/',len(R)); b.close()
