from playwright.sync_api import sync_playwright
R=[]
def T(n,ok,d=''): R.append(ok); print(('✅ ' if ok else '❌ ')+n+('' if ok else '  → '+str(d)))
with sync_playwright() as p:
    b=p.chromium.launch(args=["--no-sandbox"]); pg=b.new_page(viewport={'width':1440,'height':900}); errs=[]; warns=[]
    pg.on("pageerror",lambda e:errs.append(str(e)[:200])); pg.on("console",lambda m: warns.append(m.text[:200]) if '[drugbox]' in m.text else None)
    pg.goto('file:///tmp/drugbox_brand.html',wait_until='networkidle',timeout=60000); pg.evaluate('endSplash()'); pg.wait_for_timeout(600)
    pg.click('.lg-demo'); pg.click('#loginPage .f-btn'); pg.wait_for_timeout(3300)
    if pg.locator('.tour-skip').count(): pg.click('.tour-skip')
    # 14 + 15
    T('For-you panel on Home', pg.locator('#dxForYou .fy-card').count()==4)
    first=pg.locator('#dxForYou .fy-card').first.inner_text()
    T('match scores shown, best first', pg.evaluate("[...document.querySelectorAll('#dxForYou .fy-score b')].map(b=>+b.textContent).every((v,i,a)=>!i||a[i-1]>=v)") and 'Matches:' in first, first[:80])
    pg.locator('#dxForYou [data-role=seeker]').click(); pg.wait_for_timeout(250)
    T('role switch → job seeker home', 'Jobs that match your profile' in pg.inner_text('#dxForYou'))
    pg.locator('#dxForYou .fy-card').first.click(); pg.wait_for_timeout(900)
    T('match card opens the job, highlighted', pg.evaluate("document.body.getAttribute('data-page')")=='jobs' and pg.locator('#jx #huntingView .jcard.dx-flash').count()==1)
    pg.evaluate("goto('feed')"); pg.wait_for_timeout(400)
    T('role remembered', 'Jobs that match' in pg.inner_text('#dxForYou'))
    pg.locator('#dxForYou [data-role=supplier]').click(); pg.wait_for_timeout(250)
    pg.locator('#dxForYou .fy-card').first.click(); pg.wait_for_timeout(900)
    T('supplier: RFQ opens on the demand board', pg.locator('#mkx .dcard.dx-flash').count()==1)
    # 16
    pg.keyboard.press('Control+k'); pg.wait_for_timeout(250)
    T('Ctrl+K opens search', pg.is_visible('#dxCmd.on'))
    pg.keyboard.type('allison'); pg.wait_for_timeout(200)
    T('finds people', 'Allison Wang' in pg.inner_text('#dxCmd .cm-res'))
    pg.fill('#dxCmd input',''); pg.keyboard.type('metformin'); pg.wait_for_timeout(200)
    res=pg.inner_text('#dxCmd .cm-res')
    T('finds listings', 'LISTINGS' in res.upper() and 'Metformin' in res, res[:120])
    pg.fill('#dxCmd input',''); pg.keyboard.type('regulatory affairs'); pg.wait_for_timeout(200)
    res=pg.inner_text('#dxCmd .cm-res').upper(); T('finds jobs and groups', '\nJOBS\n' in '\n'+res and 'GROUPS' in res, res[:400])
    pg.fill('#dxCmd input',''); pg.keyboard.type('dark'); pg.wait_for_timeout(150); pg.keyboard.press('Enter'); pg.wait_for_timeout(250)
    T('commands work (dark mode)', pg.evaluate("document.documentElement.classList.contains('dx-dark')")); pg.evaluate("dxTheme('mode','light')")
    pg.keyboard.press('Control+k'); pg.keyboard.type('sara'); pg.wait_for_timeout(150)
    pg.keyboard.press('ArrowDown'); pg.keyboard.press('ArrowUp'); pg.keyboard.press('Enter'); pg.wait_for_timeout(700)
    T('keyboard ↑↓ Enter opens a result', pg.evaluate("document.body.getAttribute('data-page')") in ('jobs','profile'), pg.evaluate("document.body.getAttribute('data-page')"))
    pg.keyboard.press('Escape')
    pg.evaluate("goto('feed')"); pg.wait_for_timeout(300); pg.mouse.click(700,500); pg.keyboard.press('/'); pg.wait_for_timeout(200)
    T('"/" opens search too', pg.is_visible('#dxCmd.on')); pg.keyboard.press('Escape'); pg.wait_for_timeout(100)
    T('Esc closes', not pg.is_visible('#dxCmd.on'))
    # 17
    pg.evaluate("goto('market')"); pg.wait_for_timeout(800)
    pg.locator('#mkx .f-opt',has_text='CEP').first.locator('input').check(); pg.wait_for_timeout(400)
    T('"Save this search" appears with active filters', pg.locator('#mkx .dx-save-search').count()==1)
    pg.click('#mkx .dx-save-search'); pg.wait_for_timeout(200); pg.fill('#ssName','CEP APIs'); pg.check('input[name=ssAlert][value=weekly]'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('saved search listed', pg.locator('#mkx .dx-saved .ss-go',has_text='CEP APIs').count()==1)
    T('alert registered in notifications', pg.evaluate("NOTIFS[0].type")=='search')
    pg.locator('#mkx .dx-chip-clear').click(); pg.wait_for_timeout(300)
    cep_on=pg.locator('#mkx .f-opt',has_text='CEP').first.locator('input').is_checked()
    pg.locator('#mkx .dx-saved .ss-go',has_text='CEP APIs').click(); pg.wait_for_timeout(500)
    T('applying the saved search restores the filters', (not cep_on) and pg.locator('#mkx .f-opt',has_text='CEP').first.locator('input').is_checked())
    pg.keyboard.press('Control+k'); pg.keyboard.type('CEP APIs'); pg.wait_for_timeout(150)
    T('saved searches also in Ctrl+K', 'SAVED SEARCHES' in pg.inner_text('#dxCmd .cm-res').upper()); pg.keyboard.press('Escape')
    pg.locator('#mkx .dx-saved .ss-x').first.click(); pg.wait_for_timeout(200)
    T('delete saved search with undo', pg.locator('#mkx .dx-saved').count()==0 and pg.is_visible('#dxUndo.on'))
    pg.click('#dxUndo .u-btn'); pg.wait_for_timeout(200); T('undo brings it back', pg.locator('#mkx .dx-saved .ss-go').count()==1)
    # 18
    pg.evaluate("goto('profile')"); pg.wait_for_timeout(700)
    T('profile insights on my profile', pg.locator('.dx-insights .in-card').count()==4)
    T('views chart, viewer types, search terms', pg.locator('.dx-insights .in-bars span').count()==7 and 'Searches that found you' in pg.inner_text('.dx-insights'))
    pg.locator('.dx-insights .in-person').first.click(); pg.wait_for_timeout(600)
    T('recent viewer opens their profile', pg.locator('.dx-insights').count()==0 and pg.locator('.profile-name').count()==1)
    print('\nJS errors:',errs or 'none','| feature warnings:',warns or 'none'); print(sum(R),'/',len(R)); b.close()
