from playwright.sync_api import sync_playwright
R=[]
def T(n,ok,d=''): R.append((n,ok)); print(('✅ ' if ok else '❌ ')+n+('' if ok else '  → '+str(d)))
with sync_playwright() as p:
    b=p.chromium.launch(args=["--no-sandbox"]); pg=b.new_page(viewport={'width':1440,'height':900}); errs=[]
    pg.on("pageerror",lambda e:errs.append(str(e)[:200]))
    pg.goto('file://'+__import__('os').environ.get('DEMO_FILE','/tmp/drugbox_brand.html'),wait_until='networkidle',timeout=60000); pg.evaluate('endSplash()'); pg.wait_for_timeout(900)
    pg.click('.lg-demo'); pg.click('#loginPage .f-btn'); pg.wait_for_timeout(2200)
    pg.evaluate("goto('jobs')"); pg.wait_for_timeout(700)
    J='#jx '
    T("I'm Hiring shows candidates", pg.locator(J+'#hiringView .role-badge.need').count()==4 and pg.locator(J+'#hiringView #jobList').count()==0)
    pg.locator(J+'.mode-opt',has_text='Job Hunting').click(); pg.wait_for_timeout(200)
    T("I'm Job Hunting shows jobs", pg.locator(J+'#huntingView #jobList .jcard:visible').count()>=5)
    T('public company ratings on job cards', pg.locator(J+'#jobList .jx-rate').count()>=5 and '4.' in pg.locator(J+'#jobList .jx-rate').first.inner_text())
    T('rank badge on a top employer', pg.locator(J+'#jobList .jx-rank').count()>=1)
    pg.locator(J+'#huntingView .jx-tool',has_text='Top rated').click(); pg.wait_for_timeout(200)
    T('Top-rated employers leaderboard', '#1' in pg.inner_text('.dbk-ov') and 'Quadra' in pg.inner_text('.dbk-ov')); pg.keyboard.press('Escape')
    card=pg.locator(J+'#jobList .jcard',has_text='Beauty Lab Egypt').first
    card.locator('[data-a=write]').click(); pg.wait_for_timeout(150)
    T('review needs a real interaction', 'after applying' in pg.inner_text('.dbk-toast'))
    card.locator('.apply-btn').click(); pg.wait_for_timeout(150); pg.locator(J+'#applyModal .btn-submit').click(); pg.wait_for_timeout(250)
    T('apply unlocks review', '✓ Applied' in card.locator('.apply-btn').inner_text())
    card.locator('[data-a=write]').click(); pg.wait_for_timeout(150)
    for i in range(4): pg.locator(f'.dbk-ov .jx-stars[data-i="{i}"] .jx-star[data-v="5"]').click()
    pg.fill('#jxT','Very clear interview process, salary shared early, on time.'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('public review published, count grows', '(2)' in card.locator('.jx-rate').inner_text())
    card.locator('.jx-rate').click(); pg.wait_for_timeout(150)
    T('everyone sees reviews + anonymous author', 'Verified applicant' in pg.inner_text('.dbk-ov') and 'salary shared early' in pg.inner_text('.dbk-ov')); pg.keyboard.press('Escape')
    ep=pg.locator(J+'#jobList .jcard',has_text='Azurea').first; ep.locator('[data-a=black]').click(); pg.wait_for_timeout(150)
    pg.select_option('#blR','My current employer (confidential search)'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(250)
    T('candidate blocks a company → hidden + note', not ep.is_visible() and pg.locator(J+'#huntingView .jx-hidden-note:visible').count()==1)
    qp=pg.locator(J+'#jobList .jcard',has_text='Medsinia').first; qp.locator('[data-a=white]').click(); pg.wait_for_timeout(200)
    T('favourite company moves to top', 'Medsinia' in pg.locator(J+'#jobList .jcard:visible').first.inner_text())
    pg.locator(J+'#huntingView .jx-tool',has_text='My lists').click(); pg.wait_for_timeout(150)
    T('My lists shows whitelist', 'Medsinia' in pg.inner_text('.dbk-ov'))
    pg.locator('.dbk-ov .jx-tab',has_text='Blacklist').click(); pg.wait_for_timeout(100)
    pg.locator('.dbk-ov [data-rm]').click(); pg.wait_for_timeout(200); pg.keyboard.press('Escape')
    T('unblock brings it back', ep.is_visible())
    # employer side
    pg.locator(J+'.mode-opt',has_text="I'm Hiring").click(); pg.wait_for_timeout(200)
    T('candidate ratings by companies', 'Sara' in pg.locator(J+'#hiringView .jcard').first.inner_text() and pg.locator(J+'#hiringView .jx-rate').count()==4)
    T('honor badge on candidates', pg.locator(J+'#hiringView .jx-b.honor').count()>=3)
    T('warning badge visible to employer', pg.locator(J+'#hiringView .jx-b.warn').count()==1)
    pg.locator(J+'#hiringView .jx-b.warn').click(); pg.wait_for_timeout(150)
    T('warning shows evidence status + person\'s reply', 'Evidence verified' in pg.inner_text('.dbk-ov') and 'reply' in pg.inner_text('.dbk-ov')); pg.keyboard.press('Escape')
    nf=pg.locator(J+'#hiringView .jcard',has_text='Nour Farouk').first; nf.locator('[data-a=ref]').click(); pg.wait_for_timeout(150)
    pg.locator('.dbk-ov .jx-tab',has_text='Warning').click()
    pg.fill('#rfFrom','2024-01'); pg.fill('#rfTo','2025-06'); pg.fill('#rfRole','Formulator'); pg.fill('#rfText','Submitted a falsified stability report for batch 24-117 during the internal audit.')
    pg.select_option('#rfCat','False documents or certificates'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(150)
    T('warning requires evidence', 'needs evidence' in pg.inner_text('.dbk-toast'))
    pg.wait_for_timeout(500)   # the window ignores a second OK within 500 ms (double-click guard); a person attaching a file takes longer
    pg.set_input_files('#rfEv',files=[{'name':'audit.pdf','mimeType':'application/pdf','buffer':b'%PDF'}]); pg.check('#rfAck'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('warning goes to moderation, not published', nf.locator('.jx-b.warn').count()==0 and 'reviews the evidence' in pg.inner_text('.dbk-toast'))
    pg.locator(J+'#hiringView .jx-tool',has_text='Warning list').click(); pg.wait_for_timeout(150)
    T('own pending warning visible to its author as Pending', 'Pending review' in pg.inner_text('.dbk-ov')); pg.keyboard.press('Escape')
    ya=pg.locator(J+'#hiringView .jcard',has_text='Youssef').first; ya.locator('[data-a=ref]').click(); pg.wait_for_timeout(150)
    pg.fill('#rfFrom','2023-01'); pg.fill('#rfTo','2025-01'); pg.fill('#rfRole','QC Analyst'); pg.fill('#rfText','Built our stability-indicating HPLC method and trained the whole QC team on it.')
    pg.check('#rfAck'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('honor record published immediately', 'Honor ×2' in ya.locator('.jx-b.honor').inner_text())
    ka=pg.locator(J+'#hiringView .jcard',has_text='Karim').first; ka.locator('[data-a=black]').click(); pg.wait_for_timeout(150)
    pg.select_option('#blR','No-show at interview'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(150)
    T('employer block needs the non-discrimination confirmation', pg.locator('.dbk-ov').count()==1)
    pg.wait_for_timeout(500)   # double-click guard: the window ignores a second OK within 500 ms
    pg.check('#blAck'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(250)
    T('employer blocks candidate → hidden', not ka.is_visible())
    pg.locator(J+'#hiringView .jx-tool',has_text='Top rated').click(); pg.wait_for_timeout(150)
    T('Top-rated candidates leaderboard', 'Sara Mansour' in pg.inner_text('.dbk-ov')); pg.keyboard.press('Escape')
    pg.locator(J+'.cf-tag',has_text='QA/QC').click(); pg.wait_for_timeout(200)
    T('category filter applies to candidates too', pg.locator(J+'#hiringView .jcard:visible').count()==1)
    pg.reload(); pg.wait_for_timeout(600); pg.evaluate('endSplash()'); pg.wait_for_timeout(600); pg.click('.lg-demo'); pg.click('#loginPage .f-btn'); pg.wait_for_timeout(2000); pg.evaluate("goto('jobs')"); pg.wait_for_timeout(600)
    T('lists, reviews and references persist', not pg.locator(J+'#hiringView .jcard',has_text='Karim').first.is_visible() and 'Honor ×2' in pg.locator(J+'#hiringView .jcard',has_text='Youssef').first.inner_text())
    print('\nJS errors:',errs or 'none'); print(sum(o for _,o in R),'/',len(R)); b.close()
