from playwright.sync_api import sync_playwright
R=[]
def T(n,ok,d=''): R.append((n,ok)); print(('✅ ' if ok else '❌ ')+n+('' if ok else '  → '+str(d)))
with sync_playwright() as p:
    b=p.chromium.launch(args=["--no-sandbox"]); pg=b.new_page(viewport={'width':1440,'height':900}); errs=[]
    pg.on("pageerror",lambda e:errs.append(str(e)[:200]))
    pg.goto('file://'+__import__('os').environ.get('DEMO_FILE','/tmp/drugbox_brand.html'),wait_until='networkidle',timeout=60000); pg.evaluate('endSplash()'); pg.wait_for_timeout(900)
    pg.click('.lg-demo'); pg.click('#loginPage .f-btn'); pg.wait_for_timeout(2200)
    pg.evaluate("goto('market')"); pg.wait_for_timeout(800)
    M='#mkx '
    T('page title + pill', pg.is_visible('text=MARKETPLACE') and '1.2K LISTINGS' in pg.inner_text('.dg-pill-page'))
    n0=pg.locator(M+'.lcard:visible').count()
    pg.locator(M+'.cat-item',has_text='Services').click(); pg.wait_for_timeout(250)
    T('category tile filters', pg.locator(M+'.lcard:visible').count()==0 and pg.locator(M+'.scard:visible').count()>0)
    pg.locator(M+'.cat-item',has_text='Services').click(); pg.wait_for_timeout(250)
    T('tile again restores all', pg.locator(M+'.lcard:visible').count()==n0)
    pg.fill('#searchIn','hyaluronic'); pg.wait_for_timeout(250)
    T('top search filters marketplace live', 0<pg.locator(M+'.lcard:visible, '+M+'.sponsored-card:visible').count()<=2)
    pg.fill('#searchIn',''); pg.dispatch_event('#searchIn','input'); pg.wait_for_timeout(200)
    pg.locator(M+'.btn-contact-gold',has_text='Contact Supplier').first.click(); pg.wait_for_timeout(200)
    pg.fill('#dbkMsg','Dear Vivian, please quote 1 MT Metformin CIF Alexandria.'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('contact supplier → sent', pg.locator(M+'.btn-contact-gold.dbk-done').count()==1)
    pg.locator('.dbk-toast a').click(); pg.wait_for_timeout(700)
    T('Open chat → app Messages, right person', pg.evaluate("curPage")=='messages' and 'Vivian' in pg.inner_text('#mx .ch-name'))
    T('the sent message is in the app chat', 'Metformin CIF Alexandria' in pg.inner_text('#mx #messagesArea'))
    pg.evaluate("goto('market')"); pg.wait_for_timeout(700)
    pg.locator(M+'.dcard .qt-btn').nth(1).click(); pg.wait_for_timeout(200)
    T('demand board Quote → submit-quote form', pg.is_visible('#oPrice'))
    pg.fill('#oPrice','$3.10/kg'); pg.fill('#oQty','3 MT/month'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('quote sent', pg.locator(M+'.dcard .qt-btn.dbk-done').count()==1)
    pg.locator(M+'.dcard .qt-btn').first.click(); pg.wait_for_timeout(200)
    T('own request: no quote to yourself', 'your own request' in pg.inner_text('.dbk-toast'))
    pg.locator(M+'button',has_text='Request Quote').first.click(); pg.fill('#qQty','20'); pg.fill('#qDest','Cairo'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('RFQ to service provider', pg.locator(M+'button.dbk-done',has_text='Quote requested').count()==1)
    pg.locator(M+'.apply-btn',has_text='Apply Now').first.click(); pg.wait_for_timeout(150)
    pg.set_input_files('#aCv',files=[{'name':'CV.pdf','mimeType':'application/pdf','buffer':b'%PDF'}]); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('apply to job', pg.locator(M+'.apply-btn.dbk-done').count()==1)
    pg.locator(M+'.sp-mini').first.click(); pg.wait_for_timeout(300)
    T('featured supplier jumps to its listing', pg.locator(M+'.sponsored-card.dbk-new').count()==1)
    pg.click(M+'.js-btn'); pg.wait_for_timeout(300)
    T('+ Post a Job → job form', pg.is_visible(M+'#form-job'))
    pg.locator(M+'#form-job .field-input').first.fill('QA Manager — Sterile'); 
    for f in pg.locator(M+'#form-job .field').all():
        if f.locator('.req').count():
            i=f.locator('input:not([type=file]),textarea').first
            if i.count() and not i.input_value(): i.fill('Giza, Egypt')
    pg.click(M+'#form-job .btn-create'); pg.wait_for_timeout(300)
    T('preview shows job', pg.is_visible('#dbkPrev .jcard'))
    pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(700)
    T('job published in Jobs section', pg.locator(M+'.jobs-list .jcard',has_text='QA Manager — Sterile').count()==1)
    pg.locator(M+'.master-tab[data-tab=manage]').click(); pg.wait_for_timeout(200)
    T('My Listings visible + has new job', pg.is_visible(M+'#tab-manage') and 'QA Manager — Sterile' in pg.inner_text(M+'#tab-manage'))
    pg.locator(M+'.master-tab[data-tab=intents]').click(); pg.wait_for_timeout(200)
    T('My Intents tab visible', pg.is_visible(M+'#tab-intents'))
    pg.locator(M+'.cat-intent-row[data-cat=api] .it-opt.i-need').click(); pg.wait_for_timeout(100)
    T('intent preview updates', 'I need to buy this' in pg.inner_text(M+'#profilePreviewTags'))
    pg.evaluate("openBoostModal('featured')"); pg.wait_for_timeout(2900)
    T('boost price in EGP', 'EGP' in pg.inner_text(M+'#bmTotalEgp'))   # English interface → 'EGP 1,636' (the window follows the interface language)
    pg.click(M+'#bmPayBtn'); pg.wait_for_timeout(1500)
    T('boost payment confirms (demo)', 'Boost activated' in pg.inner_text(M+'#boostModalOverlay'))
    pg.wait_for_timeout(2300)
    for pgname in ['feed','jobs','network','notifs','profile','groups','companies','messages','market']:
        pg.evaluate(f"goto('{pgname}')"); pg.wait_for_timeout(250)
    T('navigating around and back keeps market working', pg.locator(M+'.sponsored-card').count()>0 and pg.is_visible(M+'.master-tabs'))
    print('\nJS errors:',errs or 'none'); print(sum(o for _,o in R),'/',len(R))
    b.close()
