from playwright.sync_api import sync_playwright
R=[]
def T(n,ok,d=''): R.append(ok); print(('✅ ' if ok else '❌ ')+n+('' if ok else '  → '+str(d)))
with sync_playwright() as p:
    b=p.chromium.launch(args=["--no-sandbox"]); pg=b.new_page(viewport={'width':1440,'height':900}); errs=[]; warns=[]
    pg.on("pageerror",lambda e:errs.append(str(e)[:200])); pg.on("console",lambda m: warns.append(m.text[:200]) if '[drugbox]' in m.text else None)
    pg.goto('file://'+__import__('os').environ.get('DEMO_FILE','/tmp/drugbox_brand.html'),wait_until='networkidle',timeout=60000); pg.evaluate('endSplash()'); pg.wait_for_timeout(600)
    pg.click('.lg-demo'); pg.click('#loginPage .f-btn'); pg.wait_for_timeout(3300)
    if pg.locator('.tour-skip').count(): pg.click('.tour-skip')
    DL="dxDeals"
    # own a second company: claim Cairo API Trading (so both sides are mine — no simulation)
    pg.evaluate("(()=>{var e=JSON.parse(localStorage.getItem('dx_company_edits')||'{}');e['cairo-api-trading']={owner:ME.id,status:'unverified',claimed:true};localStorage.setItem('dx_company_edits',JSON.stringify(e));localStorage.setItem('dx_acting',JSON.stringify('quadra-pharm'))})()")
    pg.evaluate("goto('companies')"); pg.wait_for_timeout(300)
    # ── quote: full life-cycle, both sides
    pg.evaluate("dxHub.page('cairo-api-trading','products')"); pg.wait_for_timeout(300)
    pg.locator('#dxDir .cp-prod',has_text='Metformin HCl API').locator('[data-hrfq]').click(); pg.wait_for_timeout(200)
    pg.fill('#rqQty','2'); pg.select_option('#rqUnit','MT'); pg.fill('#rqMsg','CEP required, monthly.'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    d=pg.evaluate(f"{DL}.all()[0]")
    T('request = one deal visible to both sides', d['type']=='quote' and d['from']['slug']=='quadra-pharm' and d['to']['slug']=='cairo-api-trading' and d['status']=='sent')
    T('no hidden timer: it stays "Sent" until the supplier acts', (pg.wait_for_timeout(500) or True) and pg.evaluate(f"{DL}.get('{d['id']}').status")=='sent')
    T('sender cannot quote their own request', pg.evaluate(f"{DL}.actionsFor({DL}.get('{d['id']}'),'from').join(',')")=='cancel')
    # switch to the supplier side
    pg.evaluate("localStorage.setItem('dx_acting',JSON.stringify('cairo-api-trading'))")
    pg.evaluate("dxHub.workspace('cairo-api-trading','deals')"); pg.wait_for_timeout(300)
    T('supplier sees it in its workspace Deals with "Your move"', 'Metformin HCl API' in pg.inner_text('#dxDir .cp-body') and 'Your move' in pg.inner_text('#dxDir .cp-body'))
    pg.locator('#dxDir .dl-row',has_text='Metformin HCl API').click(); pg.wait_for_timeout(300)
    T('deal page: parties, stepper, timeline, actions for my role', pg.locator('.dbk-ov .dl-steps li').count()==7 and pg.locator('.dbk-ov [data-act=quote]').count()==1 and pg.locator('.dbk-ov .dl-sim').count()==0)
    pg.click('.dbk-ov [data-act=quote]'); pg.wait_for_timeout(250); pg.fill('#af_price','US$ 5.20 per kg'); pg.fill('#af_lead','4 weeks'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(350)
    T('supplier sends a real quote', pg.evaluate(f"{DL}.get('{d['id']}').status")=='quoted' and 'US$ 5.20' in pg.inner_text('.dbk-ov .dl-offer'))
    pg.keyboard.press('Escape')
    # back to buyer: counter-offer, supplier re-quotes, buyer accepts
    pg.evaluate("localStorage.setItem('dx_acting',JSON.stringify('quadra-pharm'))")
    pg.evaluate(f"{DL}.thread('{d['id']}')"); pg.wait_for_timeout(250)
    T('buyer gets Accept / Counter-offer / Decline', all(pg.locator(f'.dbk-ov [data-act={a}]').count()==1 for a in ['accept','counter','decline']))
    pg.click('.dbk-ov [data-act=counter]'); pg.wait_for_timeout(250); pg.fill('#af_price','US$ 4.90 per kg'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(350); pg.keyboard.press('Escape')
    pg.evaluate("localStorage.setItem('dx_acting',JSON.stringify('cairo-api-trading'))"); pg.evaluate(f"{DL}.thread('{d['id']}')"); pg.wait_for_timeout(250)
    T('supplier sees the counter-offer', 'US$ 4.90' in pg.inner_text('.dbk-ov .dl-offer.ctr'))
    pg.click('.dbk-ov [data-act=quote]'); pg.wait_for_timeout(250); pg.fill('#af_price','US$ 5.00 per kg'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(350); pg.keyboard.press('Escape')
    pg.evaluate("localStorage.setItem('dx_acting',JSON.stringify('quadra-pharm'))"); pg.evaluate(f"{DL}.thread('{d['id']}')"); pg.wait_for_timeout(250)
    pg.click('.dbk-ov [data-act=accept]'); pg.wait_for_timeout(350); pg.keyboard.press('Escape')
    pg.evaluate("localStorage.setItem('dx_acting',JSON.stringify('cairo-api-trading'))")
    for a in ['confirm','ship']:
        pg.evaluate(f"{DL}.thread('{d['id']}')"); pg.wait_for_timeout(250); pg.click(f'.dbk-ov [data-act={a}]'); pg.wait_for_timeout(250)
        if pg.locator('.dbk-ov #af_tracking').count(): pg.fill('#af_tracking','AWB 7781-20'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
        pg.keyboard.press('Escape'); pg.wait_for_timeout(100)
    T('supplier confirms the order and ships', pg.evaluate(f"{DL}.get('{d['id']}').status")=='shipped')
    pg.evaluate("localStorage.setItem('dx_acting',JSON.stringify('quadra-pharm'))")
    pg.evaluate(f"{DL}.thread('{d['id']}')"); pg.wait_for_timeout(250); pg.click('.dbk-ov [data-act=receive]'); pg.wait_for_timeout(250); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(350); pg.keyboard.press('Escape')
    rating_before=pg.evaluate("dxDir.bySlug('cairo-api-trading').reviews")
    pg.evaluate(f"{DL}.thread('{d['id']}')"); pg.wait_for_timeout(250); pg.click('.dbk-ov [data-act=rate]'); pg.wait_for_timeout(250); pg.select_option('#af_stars','4'); pg.fill('#af_note','On time, CoA complete.'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(350)
    dd=pg.evaluate(f"{DL}.get('{d['id']}')")
    T('buyer receives (on time?) and rates → deal closed', dd['status']=='closed' and len(dd['events'])==9, (dd['status'], len(dd['events'])))
    T('supplier rating now comes from a real order', pg.evaluate("dxDir.bySlug('cairo-api-trading').reviews")==rating_before+1)
    pg.keyboard.press('Escape')
    # ── questionnaire: supplier answers, buyer approves → vendor list
    pg.evaluate("dxHub.page('cairo-api-trading')"); pg.wait_for_timeout(300)
    pg.click('#dxDir [data-hsq]'); pg.wait_for_timeout(200); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    q=pg.evaluate(f"{DL}.all().find(x=>x.type==='questionnaire')")
    T('questionnaire is a deal with pre-filled answers', q and q['status']=='sent' and len(q['answers'])>=3)
    pg.evaluate("localStorage.setItem('dx_acting',JSON.stringify('cairo-api-trading'))"); pg.evaluate(f"{DL}.thread('{q['id']}')"); pg.wait_for_timeout(250)
    pg.click('.dbk-ov [data-act=answer]'); pg.wait_for_timeout(300)
    for i in range(pg.locator('.dbk-ov input[data-req]').count()): pg.locator('.dbk-ov input[data-req]').nth(i).fill('Answered by supplier')
    pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(350); pg.keyboard.press('Escape')
    T('supplier answers (pre-filled + completed)', pg.evaluate(f"{DL}.get('{q['id']}').status")=='answered')
    pg.evaluate("localStorage.setItem('dx_acting',JSON.stringify('quadra-pharm'))"); pg.evaluate(f"{DL}.thread('{q['id']}')"); pg.wait_for_timeout(250)
    T('buyer reviews answers with their source', 'Supplier' in pg.inner_text('.dbk-ov .dl-ans') and pg.locator('.dbk-ov [data-act=approve]').count()==1)
    pg.click('.dbk-ov [data-act=approve]'); pg.wait_for_timeout(350); pg.keyboard.press('Escape')
    T('approval updates the approved vendor list', pg.evaluate("JSON.parse(localStorage.getItem('dx_avl_quadra-pharm'))['cairo-api-trading'].status")=='approved')
    # ── other side not owned: explicit simulation, never automatic
    pg.evaluate("dxHub.page('delta-analytical-labs','products')"); pg.wait_for_timeout(300)
    pg.locator('#dxDir [data-hrfq][data-hp]').first.click(); pg.wait_for_timeout(200); pg.fill('#rqQty','2'); pg.fill('#rqMsg','Two SKUs.'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    x=pg.evaluate(f"{DL}.all()[0].id"); pg.evaluate(f"{DL}.thread('{x}')"); pg.wait_for_timeout(250)
    T('other side not mine → labelled demo simulation button', pg.locator('.dbk-ov .dl-sim').count()==1)
    pg.click('.dbk-ov .dl-sim'); pg.wait_for_timeout(350)
    T('simulation performs their next step visibly', pg.evaluate(f"{DL}.get('{x}').status")=='quoted' and 'Quote received' in pg.inner_text('.dbk-ov'))
    pg.keyboard.press('Escape')
    # ── surplus: offer → counter → accept → order
    pg.evaluate("dxDir3.surplusDialog()"); pg.wait_for_timeout(250)
    pg.locator('.dbk-ov [data-soffer]').first.click(); pg.wait_for_timeout(300); pg.fill('#soP','US$ 2.10/kg'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    s=pg.evaluate(f"{DL}.all()[0]")
    T('surplus offer is a deal (offered)', s['type']=='surplus' and s['status']=='offered')
    pg.evaluate(f"{DL}.thread('{s['id']}')"); pg.wait_for_timeout(250); pg.click('.dbk-ov .dl-sim'); pg.wait_for_timeout(350)
    T('owner accepts the offer (simulated) → it becomes an order at the offered price', pg.evaluate(f"{DL}.get('{s['id']}').status")=='accepted' and pg.evaluate(f"{DL}.get('{s['id']}').offer.price")=='US$ 2.10/kg')
    pg.keyboard.press('Escape')
    pg.evaluate("dxDir3.surplusDialog()"); pg.wait_for_timeout(250); pg.locator('.dbk-ov [data-soffer]').nth(1).click(); pg.wait_for_timeout(300); pg.fill('#soP','EGP 3.00/pc'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    s2=pg.evaluate(f"{DL}.all()[0].id"); pg.evaluate(f"{DL}.act('{s2}','counter_offer',{{price:'EGP 3.60/pc'}},'to')")
    pg.evaluate(f"{DL}.thread('{s2}')"); pg.wait_for_timeout(250)
    T('counter-offer path: buyer can accept the counter', pg.locator('.dbk-ov [data-act=accept_counter]').count()==1 and 'EGP 3.60' in pg.inner_text('.dbk-ov .dl-offer.ctr'))
    pg.click('.dbk-ov [data-act=accept_counter]'); pg.wait_for_timeout(350)
    T('accepted counter becomes the order price', pg.evaluate(f"{DL}.get('{s2}').status")=='accepted' and pg.evaluate(f"{DL}.get('{s2}').offer.price")=='EGP 3.60/pc')
    pg.keyboard.press('Escape')
    # ── group: reaching the target moves it to the supplier; confirmation creates one order per member
    pg.evaluate("dxDir3.groupsDialog()"); pg.wait_for_timeout(300)
    g=pg.evaluate(f"{DL}.all().filter(x=>x.type==='group')[0]")
    need=g['lines']['target']-sum(m['qty'] for m in g['members'])
    pg.locator(f".dbk-ov [data-gq='{g['id']}']").fill(str(need)); pg.locator(f".dbk-ov [data-gjoin='{g['id']}']").click(); pg.wait_for_timeout(400)
    T('joining completes the target → waiting for the supplier', pg.evaluate(f"{DL}.get('{g['id']}').status")=='target_reached')
    pg.locator(f".dbk-ov [data-gsim='{g['id']}']").click(); pg.wait_for_timeout(400)
    orders=pg.evaluate(f"{DL}.all().filter(x=>x.groupOf==='{g['id']}').length")
    T('supplier confirms → one accepted order per member', pg.evaluate(f"{DL}.get('{g['id']}').status")=='confirmed' and orders==len(g['members'])+1, orders)
    pg.keyboard.press('Escape')
    # ── dossier: NDA → share → agree
    pg.evaluate("dxDir3.dossiersDialog()"); pg.wait_for_timeout(250); pg.locator('.dbk-ov [data-dreq]').nth(2).click(); pg.wait_for_timeout(250); pg.check('#dNda'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    dz=pg.evaluate(f"{DL}.all()[0]"); pg.evaluate(f"{DL}.thread('{dz['id']}')"); pg.wait_for_timeout(250); pg.click('.dbk-ov .dl-sim'); pg.wait_for_timeout(300); pg.click('.dbk-ov .dl-sim'); pg.wait_for_timeout(300)
    T('dossier: NDA signed → details shared', pg.evaluate(f"{DL}.get('{dz['id']}').status")=='shared')
    pg.click('.dbk-ov [data-act=agree]'); pg.wait_for_timeout(300)
    T('…→ terms agreed', pg.evaluate(f"{DL}.get('{dz['id']}').status")=='agreed')
    pg.keyboard.press('Escape')
    # ── deals centre
    pg.click('#dxDealsBtn'); pg.wait_for_timeout(250); pg.locator('.dbk-ov [data-dtab=sent]').click(); pg.wait_for_timeout(300)
    T('deals centre: Sent / Received, types, "your move"', pg.locator('.dbk-ov [data-dtab]').count()==2 and pg.locator('.dbk-ov [data-dtype]').count()==8)
    pg.locator('.dbk-ov [data-dtab=received]').click(); pg.wait_for_timeout(300)
    T('received side lists incoming deals', pg.locator('.dbk-ov .dl-row').count()>=3)
    print('\nJS errors:',errs or 'none','| feature warnings:',warns or 'none'); print(sum(R),'/',len(R)); b.close()
