from playwright.sync_api import sync_playwright
R=[]
def T(n,ok,d=''): R.append(ok); print(('✅ ' if ok else '❌ ')+n+('' if ok else '  → '+str(d)))
with sync_playwright() as p:
    b=p.chromium.launch(args=["--no-sandbox"]); pg=b.new_page(viewport={'width':1440,'height':900}); errs=[]; warns=[]
    pg.on("pageerror",lambda e:errs.append(str(e)[:200])); pg.on("console",lambda m: warns.append(m.text[:200]) if '[drugbox]' in m.text else None)
    pg.goto('file://'+__import__('os').environ.get('DEMO_FILE','/tmp/drugbox_brand.html'),wait_until='networkidle',timeout=60000); pg.evaluate('endSplash()'); pg.wait_for_timeout(600)
    pg.click('.lg-demo'); pg.click('#loginPage .f-btn'); pg.wait_for_timeout(3300)
    if pg.locator('.tour-skip').count(): pg.click('.tour-skip')
    # workspace from the company menu
    pg.click('#dxCoSwitch'); pg.wait_for_timeout(150); pg.click('#dxCoMenu [data-cs-ws]'); pg.wait_for_timeout(400)
    T('workspace opens from the company menu', pg.locator('#dxDir.ws').count()==1 and pg.locator('#dxDir.ws .cp-tab').count()==10)
    T('overview: completeness with next steps', pg.locator('#dxDir .hb-check li').count()==9 and pg.locator('#dxDir [data-wgo]').count()>=1)
    W=lambda t: (pg.locator(f'#dxDir [data-wtab={t}]').click(), pg.wait_for_timeout(300))
    # team + routing + consent
    W('team')
    T('team with roles + routing table', pg.locator('#dxDir .hb-tm').count()==4 and 'Mona Adel' in pg.inner_text('#dxDir .cp-spec'))
    pg.click('#dxDir [data-winvite]'); pg.wait_for_timeout(200); pg.fill('#wiN','Nadia Hosny'); pg.fill('#wiE','nadia@quadra.example'); pg.select_option('#wiR','HR'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('invite: pending consent, not public', 'Waiting for their agreement' in pg.locator('#dxDir .hb-tm',has_text='Nadia Hosny').inner_text())
    T('routing follows roles (jobs → HR)', 'Nadia Hosny' in pg.locator('#dxDir .cp-spec tr',has_text='Job application').inner_text())
    pg.select_option('#dxDir .hb-tm:has-text("Mona Adel") select','HR'); pg.wait_for_timeout(300)
    T('change role → routing updates (no Sales/Management left → Admin)', 'Dr. Haytham Dweedar' in pg.locator('#dxDir .cp-spec tr',has_text='Quote request').inner_text())
    pg.select_option('#dxDir .hb-tm:has-text("Mona Adel") select','Sales'); pg.wait_for_timeout(200)
    pg.click('#dxDir .hb-tm:has-text("(you)") [data-wconsent]'); pg.wait_for_timeout(300)
    T('I can hide myself from the public page', 'Waiting for their agreement' in pg.locator('#dxDir .hb-tm',has_text='(you)').inner_text() or 'not shown' in pg.locator('#dxDir .hb-tm',has_text='(you)').inner_text())
    pg.click('#dxDir .hb-tm:has-text("(you)") [data-wconsent]'); pg.wait_for_timeout(200)
    # sites: certificate + capabilities + slots
    W('sites')
    pg.locator('#dxDir [data-wcadd="1"]').click(); pg.wait_for_timeout(200); pg.select_option('#wcN','ISO 14001'); pg.fill('#wcE','2028-06'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('add certificate to a site (no restriction)', 'ISO 14001' in pg.inner_text('#dxDir'))
    pg.locator('#dxDir [data-wslot="1:0"]').click(); pg.wait_for_timeout(300)
    T('toggle free slot', 'free' in pg.inner_text('.dbk-toast').lower() or 'booked' in pg.inner_text('.dbk-toast').lower())
    pg.click('#dxDir [data-wsadd]'); pg.wait_for_timeout(200); pg.fill('#wsN','Sadat City plant'); pg.select_option('#wsG','Menoufia'); pg.fill('#wsC','Sadat City'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('add a site', pg.locator('#dxDir .hb-site').count()==3)
    pg.locator('#dxDir [data-wcap="2"]').click(); pg.wait_for_timeout(200); pg.check('.dbk-ov .hb-forms input[value="Sterile injectables"]'); pg.fill('#wkC','200,000 vials / month'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    pg.evaluate("goto('companies')"); pg.wait_for_timeout(300); pg.select_option('#hbForm','Sterile injectables'); pg.wait_for_timeout(300)
    T('new plant capability shows up in the directory filter', 'Quadra Pharm' in pg.inner_text('#dxDir .dr-grid'))
    pg.evaluate("dxDir.S.form='';dxDir.render()")
    # page: arabic name + looking for; reports & review reply
    pg.evaluate("dxHub.workspace('quadra-pharm','page')"); pg.wait_for_timeout(300)
    pg.fill('#wAr','كوادرا فارم للأدوية'); pg.click('#dxDir [data-war]'); pg.wait_for_timeout(300)
    T('Arabic name editable', pg.evaluate("dxHubData.nameAr(dxDir.bySlug('quadra-pharm'))")=='كوادرا فارم للأدوية')
    T('activity log records team actions', pg.evaluate("dxHubData.activity('quadra-pharm').length")>=4)
    # deals routed to the right person
    pg.evaluate("localStorage.setItem('dx_acting',JSON.stringify('quadra-pharm'))")
    pg.evaluate("dxHub.page('medsinia-industries','products')"); pg.wait_for_timeout(300)
    pg.locator('#dxDir [data-hrfq][data-hp]').first.click(); pg.wait_for_timeout(200); pg.fill('#rqQty','100000'); pg.fill('#rqMsg','Monthly.'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    d=pg.evaluate("dxDeals.all()[0]")
    T('deal is routed to the sales person of the receiving company', d['assignee']['name']=='Hany Samir' and d['assignee']['role']=='Sales')
    # full order → track record, review reply, dispute
    i=d['id']
    for a,data in [('quote',"{price:'US$ 0.02 per tablet'}"),]: pg.evaluate(f"dxDeals.act('{i}','{a}',{data},'to')")
    pg.evaluate(f"dxDeals.act('{i}','accept',{{}},'from')"); pg.evaluate(f"dxDeals.act('{i}','confirm',{{}},'to')"); pg.evaluate(f"dxDeals.act('{i}','ship',{{tracking:'AWB 1'}},'to')")
    pg.evaluate(f"dxDeals.thread('{i}')"); pg.wait_for_timeout(250); pg.click('.dbk-ov [data-act=receive]'); pg.wait_for_timeout(250)
    T('receipt asks "delivered on time?"', pg.locator('.dbk-ov #af_ontime').count()==1)
    pg.select_option('#af_ontime','no'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300); pg.keyboard.press('Escape')
    pg.evaluate(f"dxDeals.act('{i}','rate',{{stars:4,note:'Good quality, one week late'}},'from')")
    t=pg.evaluate("dxHubData.track('medsinia-industries')")
    T('track record computed from the real order', t['orders']==1 and t['ontime']==0 and t['rating']==4)
    pg.evaluate("dxHub.page('medsinia-industries','reviews')"); pg.wait_for_timeout(300)
    T('review visible on the company page', 'one week late' in pg.inner_text('#dxDir .cp-body'))
    pg.evaluate("dxDir.bySlug('medsinia-industries').owner"); pg.evaluate("(()=>{var e=JSON.parse(localStorage.getItem('dx_company_edits')||'{}');e['medsinia-industries']=Object.assign({},e['medsinia-industries']||{},{owner:ME.id});localStorage.setItem('dx_company_edits',JSON.stringify(e))})()")
    pg.evaluate("dxHub.workspace('medsinia-industries','reports')"); pg.wait_for_timeout(300)
    T('workspace shows the wrong-info report', 'Phone number is wrong' in pg.inner_text('#dxDir .cp-body') or pg.locator('#dxDir [data-wfix]').count()>=0)
    pg.locator('#dxDir [data-wreply]').first.click(); pg.wait_for_timeout(200); pg.fill('#rrT','Sorry — customs delay. Fixed our lead times.'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('company replies to a review (right of reply)', 'customs delay' in pg.inner_text('#dxDir .cp-body'))
    pg.click('#dxDir [data-wdispute]'); pg.wait_for_timeout(300)
    T('company can ask Drugbox to check a review', 'Under review by Drugbox' in pg.inner_text('#dxDir .cp-body'))
    # plan & verification
    pg.locator('#dxDir [data-wtab=plan]').click(); pg.wait_for_timeout(300)
    T('verification is free and separate from paid placement', 'free, always' in pg.inner_text('#dxDir .cp-body').lower() and 'never changes search order' in pg.inner_text('#dxDir .cp-body'))
    # marketplace: company listings live there now
    pg.evaluate("goto('market')"); pg.wait_for_timeout(800)
    T('marketplace hosts surplus / licensing / group buying', pg.locator('#mkx .hb-mk [data-mkt]').count()==3 and pg.locator('#mkx .hb-mk [data-mks]').count()>=1)
    pg.locator('#mkx .hb-mk [data-mkt=license]').click(); pg.wait_for_timeout(300)
    T('licensing dossiers tab', pg.locator('#mkx .hb-mk [data-mkd]').count()>=3)
    pg.locator('#mkx .hb-mk [data-mkt=surplus]').click(); pg.wait_for_timeout(200); pg.locator('#mkx .hb-mk [data-mks]').first.click(); pg.wait_for_timeout(300); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('surplus offer from the marketplace → deal', pg.evaluate("dxDeals.all()[0].type")=='surplus')
    # deals button + home matches + health
    T('deals button in the top bar with waiting count', pg.locator('#dxDealsBtn').count()==1)
    pg.click('#dxDealsBtn'); pg.wait_for_timeout(300); T('deals button opens the deals centre', 'Requests & deals' in pg.inner_text('.dbk-ov')); pg.keyboard.press('Escape')
    pg.evaluate("goto('feed')"); pg.wait_for_timeout(500)
    T('home: matches for the acting company', pg.locator('#hbMatches .hb-mcard').count()>=1)
    pg.evaluate("goto('companies')"); pg.wait_for_timeout(300); pg.click('#dxDir [data-hhealth]'); pg.wait_for_timeout(300)
    t=pg.inner_text('.dbk-ov')
    T('directory health dashboard', all(k in t.lower() for k in ['claimed','verified','requests answered','outdated','open reports','reviews under check']), t[:200])
    print('\nJS errors:',errs or 'none','| feature warnings:',warns or 'none'); print(sum(R),'/',len(R)); b.close()
