from playwright.sync_api import sync_playwright
R=[]
def T(n,ok,d=''): R.append(ok); print(('✅ ' if ok else '❌ ')+n+('' if ok else '  → '+str(d)))
with sync_playwright() as p:
    b=p.chromium.launch(args=["--no-sandbox"]); ctx=b.new_context(viewport={'width':1440,'height':900}); pg=ctx.new_page(); errs=[]; warns=[]
    pg.on("pageerror",lambda e:errs.append(str(e)[:200])); pg.on("console",lambda m: warns.append(m.text[:200]) if '[drugbox]' in m.text else None)
    pg.goto('file://'+__import__('os').environ.get('DEMO_FILE','/tmp/drugbox_brand.html'),wait_until='networkidle',timeout=60000); pg.evaluate('endSplash()'); pg.wait_for_timeout(600)
    pg.click('.lg-demo'); pg.click('#loginPage .f-btn'); pg.wait_for_timeout(3300)
    if pg.locator('.tour-skip').count(): pg.click('.tour-skip')
    pg.evaluate("goto('companies')"); pg.wait_for_timeout(400)
    cnt=lambda: pg.locator('#dxDir .hb-card').count()
    # directory = find companies
    T('directory is search + filters only (no tools bar)', cnt()==17 and pg.locator('#dxDir .dr-tools').count()==0)
    T('no levels anywhere (Gold/Silver/Bronze removed)', pg.locator('.dr-lv, .dx-lvl').count()==0 and 'Gold' not in pg.inner_text('#dxDir'))
    T('honest track record (no seeded ratings)', 'No track record yet' in pg.inner_text('#dxDir') and '★ 4.' not in pg.inner_text('#dxDir .dr-grid'))
    T('sponsored row labelled, separate from results', 'does not affect the order' in pg.inner_text('#dxDir .dr-vipstrip'))
    pg.click('#dxDir [data-hrule]'); pg.wait_for_timeout(150)
    T('published ranking rule', 'Sponsored (VIP) companies appear only' in pg.inner_text('.dbk-ov')); pg.keyboard.press('Escape')
    pg.fill('#hbQ','ميتفورمين'); pg.wait_for_timeout(600)
    T('Arabic search finds products', cnt()==3 and pg.locator('#dxDir .wm-panel').count()==1)
    T('"who makes" shows each company role', 'Registration holder · made by Obour Medica Industries' in pg.inner_text('#dxDir .wm-panel'))
    pg.fill('#hbQ',''); pg.wait_for_timeout(500)
    pg.select_option('#hbForm','Creams'); pg.wait_for_timeout(300)
    T('filter "can manufacture" (capabilities of sites)', cnt()==2 and pg.locator('#dxDir .hb-cap').count()==2)
    pg.select_option('#hbFrom','5'); pg.wait_for_timeout(300)
    T('…with free capacity from a month', cnt()==1, cnt())
    pg.click('#dxDir [data-hreset]') if pg.locator('#dxDir [data-hreset]').count() else pg.select_option('#hbForm','')
    pg.wait_for_timeout(300); pg.evaluate("dxDir.S.form='';dxDir.S.from=0;dxDir.render()"); pg.wait_for_timeout(200)
    pg.select_option('#hbGov','Alexandria'); pg.wait_for_timeout(300)
    T('governorate matches any site (Pharaonic has an Alexandria cold store)', 'Pharaonic' in pg.inner_text('#dxDir .dr-grid'))
    pg.select_option('#hbGov','All governorates'); pg.wait_for_timeout(200)
    pg.locator('#dxDir [data-hcert="ISO 9001"]').click(); pg.wait_for_timeout(300)
    T('certificate filter ignores expired certificates (Quadra ISO 9001 expired)', 'Quadra Pharm' not in pg.inner_text('#dxDir .dr-grid') and 'Medsinia' in pg.inner_text('#dxDir .dr-grid'))
    pg.locator('#dxDir [data-hcert="ISO 9001"]').click(); pg.wait_for_timeout(200)
    pg.check('#hbAct'); pg.wait_for_timeout(300)
    T('"Active this week" filter', cnt()>=3 and cnt()<17, cnt()); pg.uncheck('#hbAct'); pg.wait_for_timeout(200)
    # company page = identity
    pg.evaluate("dxHub.page('quadra-pharm')"); pg.wait_for_timeout(400)
    T('company page tabs', pg.evaluate("[...document.querySelectorAll('#dxDir .cp-tab')].map(t=>t.dataset.htab2).join(',')")=='overview,products,sites,listings,jobs,reviews,contact')
    T('Arabic company name shown', 'كوادرا فارم' in pg.inner_text('#dxDir .cp-hero'))
    T('owner sees "Open company workspace"', pg.locator('#dxDir [data-hws]').count()==1)
    T('credentials show source, site and expiry', 'Giza plant' in pg.inner_text('#dxDir .cp-body') and 'expired 2025-06' in pg.inner_text('#dxDir .cp-body'))
    T('people shown only with consent (Karim not shown)', 'Mona Adel' in pg.inner_text('#dxDir .cp-body') and 'Karim' not in pg.inner_text('#dxDir .cp-body'))
    T('source + date for the About section', 'Source: Company · updated' in pg.inner_text('#dxDir .cp-body'))
    pg.locator('#dxDir [data-htab2=sites]').click(); pg.wait_for_timeout(300)
    T('sites: certificates and capabilities per site', pg.locator('#dxDir .hb-site').count()==2 and pg.locator('#dxDir .hb-site .cap-m').count()==6)
    pg.evaluate("dxHub.page('obour-medica')"); pg.wait_for_timeout(300); pg.locator('#dxDir [data-htab2=products]').click(); pg.wait_for_timeout(300)
    T('products made for others appear on the maker page', 'Manufactured here for Nile Valley Pharmaceuticals' in pg.inner_text('#dxDir .cp-body'))
    pg.evaluate("dxHub.page('orient-cosmetics')"); pg.wait_for_timeout(300)
    T('corporate group shown', 'Ramadan Group' in pg.inner_text('#dxDir'))
    T('unclaimed page: claim banner + outdated warning', pg.locator('#dxDir [data-hclaim]').count()==1 and 'more than 6 months' in pg.inner_text('#dxDir'))
    pg.evaluate("dxHub.page('medsinia-industries')"); pg.wait_for_timeout(300)
    T('visitor actions: quote, message, follow, supplier status, questionnaire, PDF, QR, report', all(pg.locator(f'#dxDir {s}').count()==1 for s in ['[data-hrfq]','[data-hmsg]','[data-hfollow]','#hbAvl','[data-hsq]','[data-hpdf]','[data-hqr]','[data-hreport]']))
    pg.click('#dxDir [data-hreport]'); pg.wait_for_timeout(200); pg.select_option('#rpS','Contact'); pg.fill('#rpT','Phone number is wrong'); pg.fill('#rpF','+20 55 441 2299'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('report wrong information', pg.evaluate("JSON.parse(localStorage.getItem('dx_reports'))[0].slug")=='medsinia-industries')
    pg.locator('#dxDir [data-htab2=contact]').click(); pg.wait_for_timeout(300)
    T('contact tab says who answers (routing by role)', 'Hany Samir' in pg.inner_text('#dxDir .cp-body'))
    pg.locator('#dxDir [data-htab2=listings]').click(); pg.wait_for_timeout(300)
    T('listings tab: marketplace offers + surplus', 'Surplus' in pg.inner_text('#dxDir .cp-body'))
    with ctx.expect_page() as pop: pg.click('#dxDir [data-hpdf]')
    w=pop.value; w.wait_for_load_state(); T('profile PDF still works', 'Company profile generated by Drugbox' in w.content()); w.close()
    # add or claim: one company exists once
    pg.evaluate("goto('companies')"); pg.wait_for_timeout(300); pg.click('#dxDir [data-hadd]'); pg.wait_for_timeout(200); pg.fill('#acQ','nile valley'); pg.wait_for_timeout(300)
    T('add-or-claim finds the existing company first', pg.locator('.dbk-ov [data-acclaim=nile-valley-pharma]').count()==1 and pg.locator('.dbk-ov [data-acnew]').count()==1)
    pg.keyboard.press('Escape')
    print('\nJS errors:',errs or 'none','| feature warnings:',warns or 'none'); print(sum(R),'/',len(R)); b.close()
