from playwright.sync_api import sync_playwright
R=[]
def T(n,ok,d=''): R.append((n,ok)); print(('✅ ' if ok else '❌ ')+n+('' if ok else '  → '+str(d)))
with sync_playwright() as p:
    b=p.chromium.launch(args=["--no-sandbox"]); pg=b.new_page(viewport={'width':1440,'height':900}); errs=[]
    pg.on("pageerror",lambda e:errs.append(str(e)[:200]))
    pg.goto('file://'+__import__('os').environ.get('DEMO_FILE','/tmp/drugbox_brand.html'),wait_until='networkidle',timeout=60000); pg.evaluate('endSplash()'); pg.wait_for_timeout(900)
    pg.click('.lg-demo'); pg.click('#loginPage .f-btn'); pg.wait_for_timeout(2200)
    # ── JOBS
    pg.evaluate("goto('jobs')"); pg.wait_for_timeout(600)
    pg.locator('#jx .mode-opt',has_text='Job Hunting').click(); pg.wait_for_timeout(200)
    n=pg.locator('#jx #jobList .jcard:visible').count()
    pg.locator('#jx .cf-tag',has_text='QA/QC').click(); pg.wait_for_timeout(200)
    T('jobs: category filter', 0<pg.locator('#jx #jobList .jcard:visible').count()<n)
    pg.locator('#jx .cf-tag',has_text='All Jobs').click()
    pg.locator('#jx .apply-btn:visible').first.click(); pg.wait_for_timeout(200)
    T('jobs: Apply opens the approved apply form', pg.locator('#jx .jx-modal:visible, #jx [id*=pply]:visible').count()>0)
    pg.keyboard.press('Escape'); pg.evaluate("closeApplyModal && closeApplyModal()"); pg.wait_for_timeout(100)
    pg.locator('#jx .save-btn:visible').first.click(); pg.wait_for_timeout(100)
    T('jobs: save works', 'Saved' in pg.locator('#jx .save-btn:visible').first.inner_text())
    T('jobs: I\'m Job Hunting view', pg.is_visible('#jx #huntingView'))
    # ── MESSAGES from elsewhere in the app
    pg.evaluate("goto('network')"); pg.wait_for_timeout(300)
    pg.evaluate("messageUser(2)"); pg.wait_for_timeout(700)
    T('app "Message" button → approved inbox on that person', pg.evaluate("curPage")=='messages' and 'Alia' in pg.inner_text('#mx .ch-name'))
    T('no duplicate Rahmani thread', pg.locator('#mx .mx-thread',has_text='Rahmani').count()==1, pg.locator('#mx .mx-thread',has_text='Rahmani').count())
    pg.locator('#mx .mx-thread',has_text='Eng. Omar Khaled').click(); pg.wait_for_timeout(200)
    T('msg: switch thread', 'Omar' in pg.inner_text('#mx .ch-name') and 'Sounds good' in pg.inner_text('#mx #messagesArea'))
    pg.fill('#mx #composeInput','Thursday 11am works?'); pg.keyboard.press('Enter'); pg.wait_for_timeout(2900)
    T('msg: send + reply from the same person', pg.locator('#mx #messagesArea .msg-row.mx-theirs .av').last.inner_text().strip()=='OK')
    pg.click('#mx .tp-new'); pg.fill('#nmTo','Indovista Pharma'); pg.fill('#nmTx','Please share the Ciprofloxacin price list.'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(400)
    T('msg: new message', 'Indovista' in pg.inner_text('#mx .ch-name'))
    pg.locator('#mx .mx-thread',has_text='Vivian Zhou').click(); pg.wait_for_timeout(150)
    pg.click('#mx .ctx-view-btn'); pg.wait_for_timeout(800)
    T('msg: View Listing → marketplace searched', pg.evaluate("curPage")=='market' and pg.input_value('#searchIn').lower().startswith('metformin'))
    # marketplace → inbox
    pg.fill('#searchIn',''); pg.dispatch_event('#searchIn','input'); pg.wait_for_timeout(150)
    pg.locator('#mkx .sc-btn',has_text='Inquire').nth(1).click(); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    pg.locator('.dbk-toast a').click(); pg.wait_for_timeout(800)
    T('marketplace inquiry lands in the approved inbox', pg.evaluate("curPage")=='messages' and 'GCC Registration' in pg.inner_text('#mx #messagesArea'))
    pg.evaluate("goto('feed')"); pg.wait_for_timeout(300)
    pg.evaluate("document.body.click()"); pg.wait_for_timeout(100)
    # ── GROUPS
    pg.evaluate("goto('groups')"); pg.wait_for_timeout(600)
    pg.locator('#gx .cf-tag',has_text='Deal Rooms').click(); pg.wait_for_timeout(150)
    vis=pg.locator('#gx .gcard:visible').count(); deals=pg.locator('#gx .gcard:visible .gtag-deal').count()
    T('groups: Deal Rooms filter', vis>0 and vis==deals, (vis,deals))
    pg.locator('#gx .cf-tag',has_text='All Groups').click(); pg.wait_for_timeout(100)
    hb=pg.query_selector('#gx .gcard-btn.btn-join'); hb.click(); pg.wait_for_timeout(150)
    T('groups: join', 'Joined' in hb.inner_text() and not pg.is_visible('#gx #groupDetail.show'))
    pg.locator('#gx .mygroup',has_text='GCC Market Access').click(); pg.wait_for_timeout(250)
    T('groups: sidebar opens the right group', pg.inner_text('#gx #dt-title')=='GCC Market Access')
    pg.evaluate('closeGroup()')
    pg.locator('#gx .mygroup',has_text='Regulatory Affairs Egypt').click(); pg.wait_for_timeout(250)
    pg.evaluate('toggleManage()'); pg.evaluate("switchTab(document.querySelectorAll('#gx .gx-ptab')[0],'members')"); pg.wait_for_timeout(100)
    pg.locator('#gx .member-row .action-btn').first.click(); pg.locator('#gx .dd-item:visible',has_text='Message').first.click(); pg.wait_for_timeout(700)
    T('groups: member → Message opens inbox', pg.evaluate("curPage")=='messages')
    pg.evaluate("goto('groups')"); pg.wait_for_timeout(500)
    pg.evaluate('openCreate()'); pg.fill('#gx #createModal .field-input','Sterile Manufacturing Egypt'); pg.click('#gx #createModal .modal-footer .btn-create'); pg.wait_for_timeout(300)
    T('groups: create group', pg.locator('#gx .gcard-title',has_text='Sterile Manufacturing Egypt').count()==1)
    # the rest of the app still fine
    for n in ['feed','network','notifs','profile','saved','companies','training','market','jobs','messages','groups','feed']:
        pg.evaluate(f"goto('{n}')"); pg.wait_for_timeout(200)
    T('all pages navigate without errors', len(errs)==0, errs[:2])
    print('\nJS errors:',errs or 'none'); print(sum(o for _,o in R),'/',len(R))
    b.close()
