from playwright.sync_api import sync_playwright
R=[]
def T(n,ok,d=''): R.append(ok); print(('✅ ' if ok else '❌ ')+n+('' if ok else '  → '+str(d)[:220]))
with sync_playwright() as p:
    b=p.chromium.launch(args=["--no-sandbox"]); pg=b.new_page(viewport={'width':1440,'height':900}); errs=[]
    pg.on("pageerror",lambda e:errs.append(str(e)[:150]))
    pg.goto('file://'+__import__('os').environ.get('DEMO_FILE','/tmp/drugbox_brand.html'),wait_until='load'); pg.evaluate('endSplash()'); pg.wait_for_timeout(700)
    pg.click('.lg-demo'); pg.click('#loginPage button.f-btn'); pg.wait_for_timeout(2800)
    if pg.locator('.tour-skip').count(): pg.click('.tour-skip')
    E=pg.evaluate; E("localStorage.setItem('dx_acting',JSON.stringify('quadra-pharm'))")
    tiers=E("Object.fromEntries(dxDir.companies().map(c=>[c.slug,dxTiers.tierOf(c)]))")
    T('levels follow real data: Quadra & Medsinia = 3 (licensed + valid GMP site)', tiers['quadra-pharm']==3 and tiers['medsinia-industries']==3, tiers)
    T('verified but unlicensed = level 1 (Delta labs, Nile packaging)', tiers['delta-analytical-labs']==1 and tiers['nile-pharma-packaging']==1, tiers)
    T('unclaimed companies = not verified (0)', tiers['obour-medica']==0 and tiers['cairo-api-trading']==0, tiers)
    E("dxDir.S.view=null;goto('companies')"); pg.wait_for_timeout(900)
    T('directory cards show the level badge', E("document.querySelectorAll('#dxDir .hb-card .dx-tier').length")>=5, E("document.querySelectorAll('#dxDir .hb-card .dx-tier').length"))
    E("dxHub.page('medsinia-industries','overview')"); pg.wait_for_timeout(900)
    T('company page: level badge under the name', E("!!document.querySelector('#dxDir .dx-tier-h .dx-tier')"))
    T('company page: compliance passport on Overview', E("!!document.querySelector('#dxDir .dx-pass')") and 'WHO-GMP' in E("document.querySelector('#dxDir .dx-pass').innerText"))
    T('passport shows expiry from the site (valid to 2027-04)', '2027-04' in E("document.querySelector('#dxDir .dx-pass').innerText"))
    E("dxHub.page('medsinia-industries','products')"); pg.wait_for_timeout(700)
    T('passport only on Overview (not on Products)', E("!document.querySelector('#dxDir .dx-pass')"))
    E("dxHub.page('cairo-api-trading','overview')"); pg.wait_for_timeout(900)
    txt=E("(document.querySelector('#dxDir .dx-pass')||{}).innerText||''")
    T('API supplier: CEP & DMF self-declared, ASMF not provided', 'Self-declared' in txt and 'ASMF' in txt and 'Not provided' in txt, txt[:300])
    n0=E("dxDeals.all?dxDeals.all().length:(JSON.parse(localStorage.getItem('dx_deals')||'[]')).length")
    btn=pg.locator('#dxDir .dx-pass-req').first; T('"Request" button on a missing document', btn.count()==1)
    btn.click(); pg.wait_for_timeout(400)
    T('request becomes a dossier request in Requests & deals', E("[...document.querySelectorAll('#dxDir .dx-pass-req')].some(b=>b.disabled)") and E("JSON.stringify(localStorage).indexOf('Document request')>0"))
    E("dxHub.workspace('quadra-pharm','plan')"); pg.wait_for_timeout(900)
    T('workspace: ladder shows the level and the next step', E("document.querySelectorAll('#dxDir .dx-lad-s').length")==3)
    pg.click('#dxDir .dx-add-doc'); pg.wait_for_timeout(300)
    T('"Add document" opens the form', E("!!document.querySelector('.dbk-ov #pdN')"))
    pg.fill('.dbk-ov #pdP','Paracetamol'); pg.fill('.dbk-ov #pdN','R1-CEP 2020-111-Rev 01'); pg.select_option('.dbk-ov #pdT','CEP')
    pg.locator('.dbk-ov button', has_text='Save').click(); pg.wait_for_timeout(500)
    T('saved document appears as self-declared in the passport', 'R1-CEP 2020-111' in E("(document.querySelector('#dxDir .dx-pass')||{}).innerText||''"), E("(document.querySelector('.dbk-ov')||{}).innerText||'no dialog'")[:150])
    pg.reload(); pg.wait_for_timeout(1500); E("endSplash&&endSplash()"); pg.wait_for_timeout(300)
    T('document persists after reload', 'R1-CEP 2020-111' in E("JSON.stringify(dxTiers.items(dxDir.bySlug('quadra-pharm')))"))
    print('errors:', errs or 'none'); print(sum(R),'/',len(R)); b.close()
