from playwright.sync_api import sync_playwright
R=[]
def T(n,ok,d=''): R.append(ok); print(('✅ ' if ok else '❌ ')+n+('' if ok else '  → '+str(d)))
with sync_playwright() as p:
    b=p.chromium.launch(args=["--no-sandbox"]); ctx=b.new_context(viewport={'width':1440,'height':900}); pg=ctx.new_page(); errs=[]; warns=[]
    pg.on("pageerror",lambda e:errs.append(str(e)[:200])); pg.on("console",lambda m: warns.append(m.text[:200]) if '[drugbox]' in m.text else None)
    pg.goto('file://'+__import__('os').environ.get('DEMO_FILE','/tmp/drugbox_brand.html'),wait_until='networkidle',timeout=60000); pg.evaluate('endSplash()'); pg.wait_for_timeout(600)
    pg.click('.lg-demo'); pg.click('#loginPage .f-btn'); pg.wait_for_timeout(3300)
    if pg.locator('.tour-skip').count(): pg.click('.tour-skip')
    pg.evaluate("goto('companies')"); pg.wait_for_timeout(400)
    # 1 pre-populated + claim
    T('directory pre-populated (claimed + unclaimed)', pg.locator('#dxDir .dr-card').count()==17, pg.locator('#dxDir .dr-card').count())
    T('unclaimed companies labelled', pg.locator('#dxDir .dr-pend.unc').count()==8)
    pg.evaluate("dxDirectory.open('nile-valley-pharma')"); pg.wait_for_timeout(300)
    T('unclaimed page offers "Claim this page"', pg.locator('#dxDir .cp-claim [data-claim]').count()==1)
    pg.click('#dxDir .cp-claim [data-claim]'); pg.wait_for_timeout(200)
    pg.fill('#clRole','BD Manager'); pg.fill('#clPhone','01000000000'); pg.fill('#clMail','me@nilevalley.example'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    code=pg.evaluate("document.querySelector('.cl-demo b').textContent")
    pg.fill('#clCode','0000'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(150)
    T('wrong code rejected', 'Wrong code' in pg.inner_text('.dbk-toast'))
    pg.fill('#clCode',code); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(400)
    T('claimed → I manage it (Edit page, in my companies, acting as)', pg.locator('#dxDir [data-edit=all]').count()==1 and 'Nile Valley' in pg.inner_text('#dxCoSwitch'))
    T('claim banner gone', pg.locator('#dxDir .cp-claim').count()==0)
    # 2 toll finder + capabilities
    pg.evaluate("dxDirectory.open('medsinia-industries')"); pg.wait_for_timeout(300)
    T('capabilities + free slots on the page', pg.locator('#dxDir .cp-cap .cap-m.free').count()>=3)
    pg.evaluate("goto('companies')"); pg.wait_for_timeout(300)
    pg.click('#dxDir [data-finder]'); pg.wait_for_timeout(300)
    T('finder: tablets → several manufacturers ranked', pg.locator('.dbk-ov .fd-row').count()>=4, pg.locator('.dbk-ov .fd-row').count())
    pg.select_option('#fdForm','Sterile injectables'); pg.wait_for_timeout(200)
    T('finder: sterile → only the sterile plant', pg.locator('.dbk-ov .fd-row').count()==1 and 'Alexandria Sterile' in pg.inner_text('.dbk-ov .fd-res'))
    pg.select_option('#fdForm','Creams'); pg.select_option('#fdCert','ISO 22716'); pg.wait_for_timeout(200)
    first=pg.locator('.dbk-ov .fd-row').first.inner_text()
    T('finder: certificate match ranks first', 'Beauty Lab' in first, first[:80])
    pg.fill('#fdQty','40000'); pg.click('#fdSend'); pg.wait_for_timeout(300)
    T('finder → one request to the selected manufacturers', 'Request quotes from' in pg.inner_text('.dbk-ov') and 'Toll manufacturing — Creams' in pg.input_value('#bqWhat'))
    pg.fill('#bqMsg','Private label day cream, 50 g jar.'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    # 3 bulk from the list + compare
    for s in ['cairo-api-trading','alex-excipients','medsinia-industries']:
        pg.locator(f'#dxDir .dr-card[data-slug="{s}"] .dr-pick input').check(); pg.wait_for_timeout(80)
    T('select tray appears', pg.is_visible('#dxRfqTray.on') and '3' in pg.inner_text('#dxRfqTray'))
    pg.click('#dxRfqTray .tr-go'); pg.wait_for_timeout(200)
    pg.fill('#bqWhat','Metformin HCl BP'); pg.fill('#bqQty','1'); pg.select_option('#bqUnit','MT'); pg.fill('#bqMsg','Monthly, CEP required.'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('sent to 3 companies separately', pg.evaluate("dxDeals.all().filter(d=>d.title==='Metformin HCl BP').length")==3)
    gid=pg.evaluate("dxDeals.all().find(d=>d.title==='Metformin HCl BP').group")
    pg.evaluate(f"dxCompareQuotes({gid})"); pg.wait_for_timeout(300)
    T('comparison waits for real quotes (no timer)', pg.locator('.dbk-ov [data-simq]').count()==3)
    for i in range(3): pg.locator('.dbk-ov [data-simq]').first.click(); pg.wait_for_timeout(300)
    T('comparison table with lowest price marked', pg.locator('.dbk-ov .cmp tbody tr').count()==3 and pg.locator('.dbk-ov .cmp td.best').count()==1)
    pg.locator('.dbk-ov [data-accq]').first.click(); pg.wait_for_timeout(300)
    T('accept one quote → others declined', pg.evaluate(f"dxDeals.all().filter(d=>d.group==={gid}).map(d=>d.status).sort().join(',')")=='accepted,declined,declined')
    # 4 PDF + QR
    pg.evaluate("dxDirectory.open('quadra-pharm')"); pg.wait_for_timeout(300)
    pg.click('#dxDir [data-qr]'); pg.wait_for_timeout(200)
    T('QR code for the company page', pg.locator('.dbk-ov .qr-box > svg').count()==1 and 'quadra-pharm.drugbox.app' in pg.inner_text('.dbk-ov'))
    T('QR downloadable', pg.locator('.dbk-ov a[download]').count()==1)
    pg.keyboard.press('Escape')
    with ctx.expect_page() as pop:
        pg.click('#dxDir [data-pdf]')
    w=pop.value; w.wait_for_load_state(); html=w.content()
    T('profile PDF: branded page with about, products, certificates, contact and QR', 'Company profile generated by Drugbox' in html and 'Products' in html and 'Certificates' in html and '<svg' in html)
    w.close()
    # 5 active ingredient
    pg.evaluate("goto('companies')"); pg.wait_for_timeout(300); pg.fill('#drQ','metformin'); pg.wait_for_timeout(700)
    T('"Who makes Metformin in Egypt"', pg.locator('#dxDir .wm-panel').count()==1 and 'Who makes Metformin' in pg.inner_text('#dxDir .wm-panel'))
    T('lists products from several companies (finished + API)', pg.locator('#dxDir .wm-row').count()>=3, pg.locator('#dxDir .wm-row').count())
    pg.locator('#dxDir .wm-row [data-wmrfq]').first.click(); pg.wait_for_timeout(250)
    T('quote request straight from the ingredient list', 'Request a quote from' in pg.inner_text('.dbk-ov'))
    pg.keyboard.press('Escape')
    pg.fill('#drQ','packaging bottle'); pg.wait_for_timeout(600)
    T('panel only for ingredients', pg.locator('#dxDir .wm-panel').count()==0)
    print('\nJS errors:',errs or 'none','| feature warnings:',warns or 'none'); print(sum(R),'/',len(R)); b.close()
