from playwright.sync_api import sync_playwright
R=[]
def T(n,ok,d=''): R.append(ok); print(('✅ ' if ok else '❌ ')+n+('' if ok else '  → '+str(d)))
with sync_playwright() as p:
    b=p.chromium.launch(args=["--no-sandbox"]); pg=b.new_page(viewport={'width':1440,'height':900}); errs=[]; warns=[]
    pg.on("pageerror",lambda e:errs.append(str(e)[:200])); pg.on("console",lambda m: warns.append(m.text[:200]) if '[drugbox]' in m.text else None)
    pg.goto('file://'+__import__('os').environ.get('DEMO_FILE','/tmp/drugbox_brand.html'),wait_until='networkidle',timeout=60000); pg.evaluate('endSplash()'); pg.wait_for_timeout(600)
    pg.click('.lg-demo'); pg.click('#loginPage .f-btn'); pg.wait_for_timeout(3300)
    if pg.locator('.tour-skip').count(): pg.click('.tour-skip')
    pg.evaluate("goto('companies')"); pg.wait_for_timeout(400)
    T('directory tools bar (6 tools)', pg.locator('#dxDir .dr-tools .dr-tool').count()==6)
    # 1 + 2 vendor list + questionnaire
    pg.evaluate("dxDirectory.open('alex-excipients')"); pg.wait_for_timeout(300)
    T('vendor status control on supplier page', pg.locator('#dxDir .avl-ctl select').count()==1)
    pg.click('#dxDir .avl-ctl [data-sq]'); pg.wait_for_timeout(200)
    t=pg.inner_text('.dbk-ov')
    T('questionnaire pre-filled from the page', 'already filled from' in t, t[:200])
    pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('supplier moves to "Under evaluation"', 'Under evaluation' in pg.evaluate("document.querySelector('#dxDir .avl-ctl select').selectedOptions[0].textContent"))
    qid=pg.evaluate("dxDeals.all().find(d=>d.type==='questionnaire').id")
    T('questionnaire reaches the supplier (a deal)', pg.evaluate(f"dxDeals.get('{qid}').to.slug")=='alex-excipients')
    pg.evaluate(f"dxDeals.simulate('{qid}')")
    pg.evaluate("goto('companies')"); pg.wait_for_timeout(300)
    T('vendor badge on the directory card', 'Under evaluation' in pg.locator('#dxDir .dr-card[data-slug=alex-excipients]').inner_text())
    pg.locator('#dxDir .dr-tool[data-t=avl]').click(); pg.wait_for_timeout(200)
    T('approved vendor list shows answered questionnaire', pg.locator('.dbk-ov [data-sqview]').count()==1 and 'answered' in pg.inner_text('.dbk-ov') and pg.locator('.dbk-ov #avlCsv').count()==1)
    pg.locator('.dbk-ov [data-sqview]').click(); pg.wait_for_timeout(300)
    T('answers show their source (page / verified / supplier)', 'Company page' in pg.inner_text('.dbk-ov') and 'QUALITY SYSTEM' in pg.inner_text('.dbk-ov').upper())
    pg.click('.dbk-ov [data-act=approve]'); pg.wait_for_timeout(300); pg.keyboard.press('Escape'); pg.evaluate("goto('companies')"); pg.wait_for_timeout(300)
    T('approve vendor', 'Approved' in pg.locator('#dxDir .dr-card[data-slug=alex-excipients]').inner_text())
    pg.evaluate("dxDirectory.open('medsinia-industries')"); pg.wait_for_timeout(250); pg.select_option('#dxDir .avl-ctl select','suspended'); pg.wait_for_timeout(200)
    pg.evaluate("goto('companies')"); pg.wait_for_timeout(300)
    T('suspended status shows', 'Suspended' in pg.locator('#dxDir .dr-card[data-slug=medsinia-industries]').inner_text())
    # vendor list belongs to the acting company
    pg.click('#dxCoSwitch'); pg.wait_for_timeout(150)
    if pg.locator('#dxCoMenu [data-cs]').count()>1:
        pg.locator('#dxCoMenu [data-cs]').nth(1).click(); pg.wait_for_timeout(300)
        T('vendor list is per company (switching company → separate list)', 'Approved' not in pg.locator('#dxDir .dr-card[data-slug=alex-excipients]').inner_text())
        pg.click('#dxCoSwitch'); pg.wait_for_timeout(150); pg.locator('#dxCoMenu [data-cs=quadra-pharm]').click(); pg.wait_for_timeout(300)
    else:
        pg.keyboard.press('Escape'); T('vendor list is per company (only one company)', True)
    # 3 matches
    pg.locator('#dxDir .dr-tool[data-t=match]').click(); pg.wait_for_timeout(200)
    t=pg.inner_text('.dbk-ov')
    T('matches with reasons', pg.locator('.dbk-ov .mr-row').count()>=2 and ('They offer' in t or 'They look for' in t), t[:300])
    pg.keyboard.press('Escape')
    pg.evaluate("dxDirectory.open('quadra-pharm')"); pg.wait_for_timeout(300)
    T('"looking for" on the company page', 'is looking for' in pg.inner_text('#dxDir .cp-look').lower())
    pg.click('#dxDir .cp-look [data-lk]'); pg.wait_for_timeout(200); pg.fill('#lkT','Distributor — Upper Egypt\nPackaging supplier — cartons'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('owner edits what they look for', 'Packaging supplier' in pg.inner_text('#dxDir .cp-look'))
    # 4 dossiers
    T('dossiers tab on the page', pg.locator('#dxDir .cp-tab[data-tab=dossiers]').count()==1)
    pg.locator('#dxDir .cp-tab[data-tab=dossiers]').click(); pg.wait_for_timeout(300)
    T('company dossiers listed', 'Esomeprazole' in pg.inner_text('#dxDir .cp-body'))
    pg.click('#dxDir [data-dadd]'); pg.wait_for_timeout(150); pg.fill('#dsP','Rosuvastatin 10 mg tablets'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('owner adds a dossier', 'Rosuvastatin' in pg.inner_text('#dxDir .cp-body'))
    pg.evaluate("goto('companies')"); pg.wait_for_timeout(300); pg.locator('#dxDir .dr-tool[data-t=dossiers]').click(); pg.wait_for_timeout(200)
    T('all dossiers on the platform', pg.locator('.dbk-ov .mr-row').count()>=5)
    pg.locator('.dbk-ov [data-dreq]').nth(2).click(); pg.wait_for_timeout(250); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(150)
    T('dossier request needs the NDA', 'accept the NDA' in pg.inner_text('.dbk-toast'))
    pg.check('#dNda'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(250)
    T('dossier request sent (NDA → share → agree)', pg.evaluate("dxDeals.all()[0].type")=='dossier')
    # 5 group buying
    pg.locator('#dxDir .dr-tool[data-t=groups]').click(); pg.wait_for_timeout(200)
    T('open buying groups with progress', pg.locator('.dbk-ov .gb-card').count()==2 and pg.locator('.dbk-ov .gb-bar').count()==2)
    gid=pg.evaluate("dxDeals.all().filter(d=>d.type==='group').find(d=>d.lines.product.indexOf('Metformin')===0).id")
    pg.locator(f'.dbk-ov [data-gq="{gid}"]').fill('600'); pg.locator(f'.dbk-ov [data-gjoin="{gid}"]').click(); pg.wait_for_timeout(400)
    T('join a group → my share counted', 'You joined' in pg.inner_text('.dbk-ov') and '2,400' in pg.inner_text('.dbk-ov'))
    pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(250)
    pg.fill('#ngP','Lactose monohydrate DC'); pg.select_option('#ngS','alex-excipients'); pg.fill('#ngT','1000'); pg.fill('#ngQ','300'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(400)
    T('start a new group', pg.locator('.dbk-ov .gb-card').count()==3 and 'Lactose' in pg.inner_text('.dbk-ov'))
    pg.keyboard.press('Escape')
    # 6 surplus
    pg.locator('#dxDir .dr-tool[data-t=surplus]').click(); pg.wait_for_timeout(200)
    T('surplus stock with discount, batch, expiry', pg.locator('.dbk-ov .sp-off').count()==4 and 'batch' in pg.inner_text('.dbk-ov'))
    pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(250)
    pg.fill('#spP','Gelatin capsules size 0'); pg.fill('#spQ','2,000,000 pcs'); pg.fill('#spR','EGP 0.05/pc'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(400)
    T('post surplus', 'Gelatin capsules' in pg.inner_text('.dbk-ov'))
    pg.locator('.dbk-ov [data-soffer]').nth(1).click(); pg.wait_for_timeout(400)
    pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('make an offer → surplus deal', pg.evaluate("dxDeals.all()[0].type")=='surplus')
    pg.keyboard.press('Escape')
    # 7 memberships
    pg.evaluate("dxDirectory.open('quadra-pharm')"); pg.wait_for_timeout(300)
    T('confirmed membership badges', pg.locator('#dxDir .mb-badge:not(.pend)').count()==2)
    pg.click('#dxDir [data-addmb]'); pg.wait_for_timeout(150); pg.select_option('#mbB','Egyptian Pharmaceutical Trading Association'); pg.fill('#mbN','EPTA-2291'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('new membership waits for the organisation', pg.locator('#dxDir .mb-badge.pend').count()==1)
    print('\nJS errors:',errs or 'none','| feature warnings:',warns or 'none'); print(sum(R),'/',len(R)); b.close()
