from playwright.sync_api import sync_playwright
R=[]
def T(n,ok,d=''): R.append(ok); print(('✅ ' if ok else '❌ ')+n+('' if ok else '  → '+str(d)))
with sync_playwright() as p:
    b=p.chromium.launch(args=["--no-sandbox"]); pg=b.new_page(viewport={'width':1440,'height':900}); errs=[]; warns=[]
    pg.on("pageerror",lambda e:errs.append(str(e)[:200])); pg.on("console",lambda m: warns.append(m.text[:200]) if '[drugbox]' in m.text else None)
    pg.goto('file://'+__import__('os').environ.get('DEMO_FILE','/tmp/drugbox_brand.html'),wait_until='networkidle',timeout=60000); pg.evaluate('endSplash()'); pg.wait_for_timeout(600)
    pg.click('.lg-demo'); pg.click('#loginPage .f-btn'); pg.wait_for_timeout(3300)
    if pg.locator('.tour-skip').count(): pg.click('.tour-skip')
    T('sidebar says Company Directory', 'Company Directory' in pg.inner_text('#snl-companies'))
    pg.click('#snl-companies'); pg.wait_for_timeout(500)
    T('directory lists companies', pg.locator('#dxDir .dr-card').count()==17, pg.locator('#dxDir .dr-card').count())
    T('no old Market Board header or band', pg.locator('#content .dg-page-head, #content .dg-band').count()==0 and 'ENQUIRIES' not in pg.inner_text('#content'))
    pg.locator('#dxDir .dr-chip',has_text='Packaging').click(); pg.wait_for_timeout(200)
    T('filter by activity', pg.locator('#dxDir .dr-card').count()==2 and 'Nile Pharma Packaging' in pg.inner_text('#dxDir .dr-grid') and 'Suez Pharma Packaging' in pg.inner_text('#dxDir .dr-grid'))
    pg.locator('#dxDir .dr-chip',has_text='All').first.click(); pg.select_option('#drGov','Alexandria'); pg.wait_for_timeout(200)
    T('filter by governorate', pg.locator('#dxDir .dr-card').count()==3)
    pg.select_option('#drGov','All governorates'); pg.wait_for_timeout(150)
    pg.fill('#drQ','MCC'); pg.wait_for_timeout(450)
    T('search finds by product', pg.locator('#dxDir .dr-card').count()==1 and 'Alex Excipients' in pg.inner_text('#dxDir .dr-grid'))
    T('search box keeps focus while typing', pg.evaluate("document.activeElement && document.activeElement.id")=='drQ')
    pg.fill('#drQ',''); pg.wait_for_timeout(450)
    pg.locator('#dxDir .dr-chip',has_text='WHO-GMP').click(); pg.wait_for_timeout(200)
    T('filter by certificate', pg.locator('#dxDir .dr-card').count()==2)
    pg.locator('#dxDir .dr-chip',has_text='WHO-GMP').click(); pg.wait_for_timeout(150)
    pg.locator('#dxDir .dr-card',has_text='Delta Analytical').locator('[data-go]').click(); pg.wait_for_timeout(300)
    T('company page opens (mini website)', pg.locator('#dxDir .cp-hero .cp-name').inner_text().startswith('Delta Analytical Labs'))
    T('opens at the top', pg.evaluate("document.getElementById('content').scrollTop")==0)
    pg.locator('#dxDir .cp-tab[data-tab=products]').click(); pg.wait_for_timeout(200)
    T('product catalogue with pictures', pg.locator('#dxDir .cp-prod img').count()==2)
    pg.locator('#dxDir .cp-pimg').first.click(); pg.wait_for_timeout(200)
    T('product details with specs', pg.locator('.dbk-ov .cp-spec').count()==1)
    pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('quote request form opens from product', 'Request a quote from Delta Analytical Labs' in pg.inner_text('.dbk-ov'))
    pg.fill('#rqQty','2'); pg.select_option('#rqUnit','batches'); pg.fill('#rqMsg','Two products, Zone IVa, need report in English.'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(500)
    T('request sent → a deal with the company', pg.evaluate("dxDeals.all()[0].to.slug")=='delta-analytical-labs' and pg.evaluate("dxDeals.all()[0].status")=='sent')
    pg.locator('#dxDir .cp-tab[data-tab=contact]').click(); pg.wait_for_timeout(200)
    links=pg.evaluate("[...document.querySelectorAll('#dxDir .cp-contact a')].map(a=>a.getAttribute('href'))")
    T('contact: phone, email, WhatsApp, website, map', any(l.startswith('tel:') for l in links) and any(l.startswith('mailto:') for l in links) and any('wa.me' in l for l in links) and any('google.com/maps' in l for l in links), links)
    pg.locator('#dxDir .cp-tab[data-tab=jobs]').click(); pg.wait_for_timeout(200)
    pg.locator('#dxDir [data-apply]').first.click(); pg.wait_for_timeout(200); pg.fill('#apMsg','5 years HPLC, method validation and stability.'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(200)
    T('job only on the company page: application needs a CV', 'attach your CV' in pg.inner_text('.dbk-toast'))
    pg.set_input_files('#apCv',files=[{'name':'cv.pdf','mimeType':'application/pdf','buffer':b'%PDF'}]); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('job application sent', 'Application sent' in pg.inner_text('.dbk-toast'))
    pg.locator('#dxDir [data-follow]').first.click(); pg.wait_for_timeout(200)
    T('follow company', '✓ Following' in pg.inner_text('#dxDir .cp-cta'))
    pg.click('#dxDir .cp-back'); pg.wait_for_timeout(200)
    T('back to all companies', pg.locator('#dxDir .dr-card').count()==17)
    # owner
    pg.locator('#dxDir [data-mycos]').click(); pg.wait_for_timeout(250); pg.locator('.dbk-ov [data-open2=quadra-pharm]').click(); pg.wait_for_timeout(300)
    pg.locator('#dxDir [data-edit=all]').click(); pg.wait_for_timeout(300)
    T('owner: My companies → my page → editor', pg.is_visible('#dxEditor') and 'Quadra Pharm' in pg.inner_text('#dxDir .cp-name'))
    pg.fill('#edTag','WHO-GMP manufacturing and EDA registration — one partner.'); pg.click('#edAddP'); pg.wait_for_timeout(150)
    pg.fill('#edPName','Vitamin D3 Drops'); pg.select_option('#edPCat','Supplements'); pg.select_option('#edPKind','bottle'); pg.fill('#edPMoq','5,000 bottles')
    import base64, io
    from PIL import Image
    im=Image.new('RGB',(600,600),(40,120,220)); buf=io.BytesIO(); im.save(buf,'JPEG')
    pg.set_input_files('#edPFile',files=[{'name':'d3.jpg','mimeType':'image/jpeg','buffer':buf.getvalue()}]); pg.wait_for_timeout(400)
    T('uploaded product photo previews', pg.evaluate("document.getElementById('edPImg').src.startsWith('data:image/jpeg')"))
    pg.click('#edPSave'); pg.wait_for_timeout(150); pg.click('#edSave'); pg.wait_for_timeout(400)
    T('page published with new tagline', 'one partner' in pg.inner_text('#dxDir .cp-tagline'))
    pg.locator('#dxDir .cp-tab[data-tab=products]').click(); pg.wait_for_timeout(200)
    T('new product with real photo on the page', pg.locator('#dxDir .cp-prod',has_text='Vitamin D3 Drops').locator('img').get_attribute('src').startswith('data:image/jpeg'))
    pg.locator('#dxDir .cp-tab[data-tab=requests]').click(); pg.wait_for_timeout(200)
    T('owner Requests tab lists received deals', pg.locator('#dxDir .cp-body .dl-row').count()>=3)
    pg.reload(); pg.wait_for_timeout(600); pg.evaluate('endSplash()'); pg.wait_for_timeout(500); pg.click('.lg-demo'); pg.click('#loginPage .f-btn'); pg.wait_for_timeout(3300)
    if pg.locator('.tour-skip').count(): pg.click('.tour-skip')
    pg.evaluate("dxDirectory.open('quadra-pharm','products')"); pg.wait_for_timeout(400)
    T('edits persist after reload', pg.locator('#dxDir .cp-prod',has_text='Vitamin D3 Drops').count()==1)
    pg.keyboard.press('Control+k'); pg.keyboard.type('lactose'); pg.wait_for_timeout(200)
    T('Ctrl+K finds company products', 'Lactose' in pg.inner_text('#dxCmd .cm-res'))
    pg.keyboard.press('Enter'); pg.wait_for_timeout(400)
    T('…and opens the company products tab', 'Alex Excipients' in pg.inner_text('#dxDir .cp-name') and pg.locator('#dxDir .cp-tab.on[data-tab=products]').count()==1)
    pg.evaluate("goto('feed')"); pg.wait_for_timeout(300); pg.click('#snl-companies'); pg.wait_for_timeout(300)
    T('sidebar returns to the full directory', pg.locator('#dxDir .dr-card').count()==17)
    pg.evaluate("dxDirectory.open('regpath-consulting')"); pg.wait_for_timeout(250); pg.evaluate("goto('feed')"); pg.wait_for_timeout(200); pg.evaluate("goto('companies')"); pg.wait_for_timeout(250)
    T('opening the page from anywhere shows the list', pg.locator('#dxDir .dr-card').count()==17)
    print('\nJS errors:',errs or 'none','| feature warnings:',warns or 'none'); print(sum(R),'/',len(R)); b.close()
