from playwright.sync_api import sync_playwright
import io
from PIL import Image
R=[]
def T(n,ok,d=''): R.append(ok); print(('✅ ' if ok else '❌ ')+n+('' if ok else '  → '+str(d)))
def pdf(n): return {'name':n,'mimeType':'application/pdf','buffer':b'%PDF'}
with sync_playwright() as p:
    b=p.chromium.launch(args=["--no-sandbox"]); pg=b.new_page(viewport={'width':1440,'height':900}); errs=[]; warns=[]
    pg.on("pageerror",lambda e:errs.append(str(e)[:200])); pg.on("console",lambda m: warns.append(m.text[:200]) if '[drugbox]' in m.text else None)
    pg.goto('file://'+__import__('os').environ.get('DEMO_FILE','/tmp/drugbox_brand.html'),wait_until='networkidle',timeout=60000); pg.evaluate('endSplash()'); pg.wait_for_timeout(600)
    pg.click('.lg-demo'); pg.click('#loginPage .f-btn'); pg.wait_for_timeout(3300)
    if pg.locator('.tour-skip').count(): pg.click('.tour-skip')
    pg.evaluate("goto('companies')"); pg.wait_for_timeout(400)
    T('"Create a company page" always visible', pg.locator('#dxDir [data-create]').count()==1)
    T('VIP companies strip, marked Sponsored', pg.locator('#dxDir .dr-vipstrip .dr-vs-card').count()>=3 and 'Sponsored' in pg.inner_text('#dxDir .dr-vipstrip'))
    T('VIP badge separate from partner level', pg.locator('#dxDir .dr-card',has_text='Quadra Pharm').locator('.dr-vip').count()==1 and pg.locator('#dxDir .dr-card',has_text='Quadra Pharm').locator('.dr-lv').count()==1)
    T('VIP companies listed first', pg.evaluate("[...document.querySelectorAll('#dxDir .dr-grid .dr-card')].slice(0,3).every(c=>c.querySelector('.dr-vip'))"))
    T('acting-as selector for owners', pg.locator('#drActing').count()==1)
    # wizard
    pg.click('#dxDir [data-create]'); pg.wait_for_timeout(250)
    T('step 1: Basic vs VIP plans with prices', pg.locator('.dbk-ov .pl-card').count()==2 and 'EGP 2,500' in pg.inner_text('.dbk-ov'))
    pg.locator('.dbk-ov input[name=plBill][value=year]').check(); pg.wait_for_timeout(150)
    T('yearly pricing', 'EGP 25,000' in pg.inner_text('.dbk-ov'))
    pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(250)
    pg.fill('#ccN','Nova Cosmetics Egypt'); pg.select_option('#ccS','Cosmetics'); pg.select_option('#ccG','Giza'); pg.fill('#ccC','6th of October'); pg.fill('#ccP','+20 2 3800 1234'); pg.fill('#ccE','info@nova.example'); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(250)
    T('no documents step: details → review', pg.locator('.dbk-ov #ccR').count()==0 and '3 of 3' in pg.inner_text('.dbk-ov'))
    txt=pg.inner_text('.dbk-ov')
    T('step 4: review with VAT and total in EGP', 'VAT 14%' in txt and '28,500' in txt, txt[:200])
    pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(600)
    T('company created → its page opens with the editor', 'Nova Cosmetics Egypt' in pg.inner_text('#dxDir .cp-name') and pg.is_visible('#dxEditor'))
    T('page is live, labelled Not verified, with Get verified', 'Not verified' in pg.inner_text('#dxDir .cp-banner.pend') and pg.locator('#dxDir [data-verify]').count()==1)
    T('editor opens with cover upload', pg.locator('#dxEditor #edCover').count()==1)
    pg.click('#dxEditor .ed-x'); pg.wait_for_timeout(200)
    pg.evaluate("goto('companies')"); pg.wait_for_timeout(300)
    T('new company listed with a Not verified chip', 'Not verified' in pg.locator('#dxDir .dr-card',has_text='Nova Cosmetics Egypt').inner_text())
    T('new VIP company appears in the VIP strip', 'Nova Cosmetics' in pg.inner_text('#dxDir .dr-vipstrip'))
    T('other users see it too (public, clearly unverified)', pg.evaluate("ME.id=777, dxDirectory.list().some(c=>c.name==='Nova Cosmetics Egypt')")==True); pg.evaluate("ME.id=1")
    pg.evaluate("dxDirectory.open('nova-cosmetics-egypt')"); pg.wait_for_timeout(250); pg.locator('#dxDir [data-verify]').click(); pg.wait_for_timeout(200)
    pg.fill('#vfRN','100100'); pg.set_input_files('#vfR',files=[pdf('r.pdf')]); pg.set_input_files('#vfT',files=[pdf('t.pdf')]); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(200)
    pg.wait_for_timeout(300)
    T('Get verified: documents sent → verification in review', 'Verification in review' in pg.inner_text('#dxDir .cp-banner.pend'))
    # acting as a pending company → medicines blocked with the reason
    pg.evaluate("goto('companies')"); pg.wait_for_timeout(300)
    pg.select_option('#drActing','nova-cosmetics-egypt'); pg.wait_for_timeout(150)
    pg.evaluate("dxDirectory.open('medsinia-industries','products')"); pg.wait_for_timeout(300)
    pg.locator('#dxDir .cp-prod',has_text='Paracetamol').locator('[data-rfq]').click(); pg.wait_for_timeout(200)
    T('medicines: notice only, request still allowed', 'Egyptian law' in pg.inner_text('.dbk-ov') and pg.locator('.dbk-ov #rqQty').count()==1)
    pg.keyboard.press('Escape'); pg.wait_for_timeout(100)
    pg.evaluate("goto('companies')"); pg.wait_for_timeout(300); pg.select_option('#drActing','quadra-pharm'); pg.wait_for_timeout(100)
    pg.evaluate("dxDirectory.open('medsinia-industries','products')"); pg.wait_for_timeout(300)
    pg.locator('#dxDir .cp-prod',has_text='Paracetamol').locator('[data-rfq]').click(); pg.wait_for_timeout(200)
    T('shows which company is requesting', 'Quadra Pharm' in ' '.join(pg.locator('.dbk-ov .rq-to').all_inner_texts()) and pg.locator('.dbk-ov #rqQty').count()==1)
    pg.keyboard.press('Escape')
    # Basic plan limits + upgrade
    pg.evaluate("dxDirectory.open('medsinia-industries')"); pg.wait_for_timeout(200)
    pg.evaluate("ME.id=5"); pg.evaluate("dxDirectory.open('medsinia-industries')"); pg.wait_for_timeout(300)
    T('Basic owner sees an optional VIP offer (no limits)', 'See VIP' in pg.inner_text('#dxDir .cp-banner.up') and 'Up to 5' not in pg.inner_text('#dxDir'))
    pg.locator('#dxDir [data-edit=all]').click(); pg.wait_for_timeout(250)
    T('Basic: cover photo available', pg.locator('#dxEditor #edCover').count()==1)
    pg.click('#edAddP'); pg.wait_for_timeout(100); pg.fill('#edPName','P4'); pg.click('#edPSave'); pg.wait_for_timeout(100)
    pg.click('#edAddP'); pg.wait_for_timeout(100); pg.fill('#edPName','P5'); pg.click('#edPSave'); pg.wait_for_timeout(100)
    pg.click('#edAddP'); pg.wait_for_timeout(100); pg.fill('#edPName','P6'); pg.click('#edPSave'); pg.wait_for_timeout(100)
    pg.click('#edAddP'); pg.wait_for_timeout(100); pg.fill('#edPName','P7'); pg.click('#edPSave'); pg.wait_for_timeout(100)
    T('Basic: no product limit (7 products)', pg.locator('#dxEditor .ed-prod').count()==7, pg.locator('#dxEditor .ed-prod').count())
    pg.click('#dxEditor .ed-x'); pg.wait_for_timeout(150)
    pg.locator('#dxDir [data-upgrade]').first.click(); pg.wait_for_timeout(200); pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(250)
    T('upgrade shows payment in EGP', 'EGP' in pg.inner_text('.dbk-ov') and 'VAT' in pg.inner_text('.dbk-ov'))
    pg.click('.dbk-ov [data-a=ok]'); pg.wait_for_timeout(300)
    T('upgraded → VIP badge on the page', pg.locator('#dxDir .cp-name .dr-vip').count()==1)
    pg.evaluate("ME.id=1")
    # entry points
    pg.evaluate("goto('profile')"); pg.wait_for_timeout(500)
    T('profile: My companies card with Create', pg.locator('.dx-mycos .mc-co').count()==2 and pg.locator('.dx-mycos [data-mcnew]').count()==1)
    pg.keyboard.press('Control+k'); pg.keyboard.type('create a company'); pg.wait_for_timeout(200)
    T('Ctrl+K: Create a company page', 'Create a company page' in pg.inner_text('#dxCmd .cm-res'))
    pg.keyboard.press('Enter'); pg.wait_for_timeout(400)
    T('…opens the wizard', pg.locator('.dbk-ov .pl-card').count()==2)
    print('\nJS errors:',errs or 'none','| feature warnings:',warns or 'none'); print(sum(R),'/',len(R)); b.close()
