"""The five launch quick-entry templates as data rows (templates/<id>).

Mirror of `defaultTemplates()` in src/engine/templates.js (account codes and Arabic labels are configuration, no company
data). tests/seed/test_seed.py compares this module with the live engine output when node is available, so a change on
either side is noticed.
"""

TEMPLATES = {'tpl-salary-accrual': {'id': 'tpl-salary-accrual',
                        'name': 'استحقاق مرتب',
                        'order': 1,
                        'active': True,
                        'inputs': [{'key': 'party', 'label': 'الموظف', 'type': 'party', 'required': True},
                                   {'key': 'monthly', 'label': 'المرتب الشهري', 'type': 'amount', 'required': True},
                                   {'key': 'months',
                                    'label': 'عدد الأشهر',
                                    'type': 'number',
                                    'required': True,
                                    'default': 1},
                                   {'key': 'expenseAcct',
                                    'label': 'حساب المصروف',
                                    'type': 'account',
                                    'required': True,
                                    'default': '5210'},
                                   {'key': 'date', 'label': 'التاريخ', 'type': 'date', 'required': True},
                                   {'key': 'docIds', 'label': 'المستند', 'type': 'docs', 'required': False},
                                   {'key': 'cc', 'label': 'مركز التكلفة', 'type': 'select-cc', 'required': False},
                                   {'key': 'sector',
                                    'label': 'القطاع القانوني',
                                    'type': 'select-sector',
                                    'required': False}],
                        'defaults': {'cc': 'input:cc', 'sector': 'input:sector', 'docIds': []},
                        'lines': [{'side': 'dr',
                                   'acctFrom': 'input:expenseAcct',
                                   'amountFrom': 'input:monthly*input:months',
                                   'partyFrom': 'none'},
                                  {'side': 'cr',
                                   'acctFrom': 'party.defaultAccount',
                                   'amountFrom': 'input:monthly*input:months',
                                   'partyFrom': 'input:party'}],
                        'descPattern': 'استحقاق مرتب {partyName} عن {months} شهر',
                        'rule': None},
 'tpl-expense-paid': {'id': 'tpl-expense-paid',
                      'name': 'مصروف مدفوع',
                      'order': 2,
                      'active': True,
                      'inputs': [{'key': 'expenseAcct', 'label': 'حساب المصروف', 'type': 'account', 'required': True},
                                 {'key': 'payAcct',
                                  'label': 'الدفع من',
                                  'type': 'select',
                                  'required': True,
                                  'options': ['1320', '1340']},
                                 {'key': 'amount', 'label': 'المبلغ', 'type': 'amount', 'required': True},
                                 {'key': 'payee', 'label': 'المستلم', 'type': 'text', 'required': False},
                                 {'key': 'ref', 'label': 'رقم الشيك / المرجع', 'type': 'text', 'required': False},
                                 {'key': 'date', 'label': 'التاريخ', 'type': 'date', 'required': True},
                                 {'key': 'docIds', 'label': 'المستند', 'type': 'docs', 'required': False},
                                 {'key': 'cc', 'label': 'مركز التكلفة', 'type': 'select-cc', 'required': False},
                                 {'key': 'sector',
                                  'label': 'القطاع القانوني',
                                  'type': 'select-sector',
                                  'required': False}],
                      'defaults': {'cc': 'input:cc', 'sector': 'input:sector', 'docIds': []},
                      'lines': [{'side': 'dr',
                                 'acctFrom': 'input:expenseAcct',
                                 'amountFrom': 'input:amount',
                                 'partyFrom': 'none'},
                                {'side': 'cr',
                                 'acctFrom': 'input:payAcct',
                                 'amountFrom': 'input:amount',
                                 'partyFrom': 'none'}],
                      'descPattern': 'صرف[ {ref}][ — {payee}]',
                      'rule': None},
 'tpl-funding': {'id': 'tpl-funding',
                 'name': 'تمويل من طرف',
                 'order': 3,
                 'active': True,
                 'inputs': [{'key': 'party', 'label': 'الممول', 'type': 'party', 'required': True},
                            {'key': 'amount', 'label': 'المبلغ', 'type': 'amount', 'required': True},
                            {'key': 'evidence',
                             'label': 'ما الذي يثبته؟',
                             'type': 'select',
                             'required': True,
                             'options': ['bank', 'treasury', 'none']},
                            {'key': 'landAcct',
                             'label': 'دخل إلى',
                             'type': 'select',
                             'required': True,
                             'options': ['1340', '1320'],
                             'default': '1340'},
                            {'key': 'ref', 'label': 'المرجع', 'type': 'text', 'required': False},
                            {'key': 'date', 'label': 'التاريخ', 'type': 'date', 'required': True},
                            {'key': 'docIds', 'label': 'المستند', 'type': 'docs', 'required': False},
                            {'key': 'cc', 'label': 'مركز التكلفة', 'type': 'select-cc', 'required': False},
                            {'key': 'sector',
                             'label': 'القطاع القانوني',
                             'type': 'select-sector',
                             'required': False}],
                 'defaults': {'cc': 'input:cc', 'sector': 'input:sector', 'docIds': []},
                 'lines': [{'side': 'dr',
                            'acctFrom': 'input:landAcct',
                            'amountFrom': 'input:amount',
                            'partyFrom': 'none'},
                           {'side': 'cr',
                            'acctFrom': 'party.defaultAccount',
                            'amountFrom': 'input:amount',
                            'partyFrom': 'input:party'}],
                 'descPattern': 'تمويل من {partyName}[ — {ref}]',
                 'rule': 'cash-funding-evidence'},
 'tpl-unknown-deposit': {'id': 'tpl-unknown-deposit',
                         'name': 'إيداع غير محدد المصدر',
                         'order': 4,
                         'active': True,
                         'inputs': [{'key': 'amount', 'label': 'المبلغ', 'type': 'amount', 'required': True},
                                    {'key': 'landAcct',
                                     'label': 'دخل إلى',
                                     'type': 'select',
                                     'required': True,
                                     'options': ['1340', '1320'],
                                     'default': '1340'},
                                    {'key': 'party',
                                     'label': 'الطرف («غير محدد»)',
                                     'type': 'party',
                                     'required': True},
                                    {'key': 'ref', 'label': 'المرجع', 'type': 'text', 'required': False},
                                    {'key': 'date', 'label': 'التاريخ', 'type': 'date', 'required': True},
                                    {'key': 'docIds', 'label': 'المستند', 'type': 'docs', 'required': False},
                                    {'key': 'cc', 'label': 'مركز التكلفة', 'type': 'select-cc', 'required': False},
                                    {'key': 'sector',
                                     'label': 'القطاع القانوني',
                                     'type': 'select-sector',
                                     'required': False}],
                         'defaults': {'cc': 'input:cc', 'sector': 'input:sector', 'docIds': []},
                         'lines': [{'side': 'dr',
                                    'acctFrom': 'input:landAcct',
                                    'amountFrom': 'input:amount',
                                    'partyFrom': 'none'},
                                   {'side': 'cr',
                                    'acctFrom': 'fixed:2160',
                                    'amountFrom': 'input:amount',
                                    'partyFrom': 'input:party'}],
                         'descPattern': 'إيداع غير محدد المصدر[ — {ref}]',
                         'rule': 'open-item-on-unknown-source'},
 'tpl-bank-to-cash': {'id': 'tpl-bank-to-cash',
                      'name': 'سحب من البنك للخزينة',
                      'order': 5,
                      'active': True,
                      'inputs': [{'key': 'amount', 'label': 'المبلغ', 'type': 'amount', 'required': True},
                                 {'key': 'ref', 'label': 'رقم الشيك / المستلم', 'type': 'text', 'required': False},
                                 {'key': 'date', 'label': 'التاريخ', 'type': 'date', 'required': True},
                                 {'key': 'docIds', 'label': 'المستند', 'type': 'docs', 'required': False},
                                 {'key': 'cc', 'label': 'مركز التكلفة', 'type': 'select-cc', 'required': False},
                                 {'key': 'sector',
                                  'label': 'القطاع القانوني',
                                  'type': 'select-sector',
                                  'required': False}],
                      'defaults': {'cc': 'input:cc', 'sector': 'input:sector', 'docIds': []},
                      'lines': [{'side': 'dr',
                                 'acctFrom': 'fixed:1320',
                                 'amountFrom': 'input:amount',
                                 'partyFrom': 'none'},
                                {'side': 'cr',
                                 'acctFrom': 'fixed:1340',
                                 'amountFrom': 'input:amount',
                                 'partyFrom': 'none'}],
                      'descPattern': 'سحب من البنك للخزينة[ — {ref}]',
                      'rule': None}}


def templates():
    import copy
    return copy.deepcopy(TEMPLATES)
